### ISSUE TITLE
`lint` called too frequently resulting in spurious warnings

### ISSUE THREAD

**Issue by neilvyas** [palantir/python-language-server#106]
The really annoying one is `W291` trailing whitespace. I wouldn't want to disable this warning because it's actually useful (although you can highlight trailing whitespace anyway), but since the `lint` command runs on every change, then every time you enter a space, the warning appears. In `nvim` this means my signcolumn / gutter is constantly appearing and re-appearing, which makes the text area shift left and right a column.

I think the problem could be remedied with more logic [here](https://github.com/palantir/python-language-server/blob/develop/pyls/python_ls.py#L112#L119) instead of calling `self.lint` on every change. Maybe every line would be a better frequency?

I would be happy to implement this at some point.

**Comment by gatesn** [comment]
Sounds good, seems like we need to debounce to ~200ms here, maybe higher. That's the reason `lint` is decoupled from `didChange` anyway.

**Comment by tomv564** [comment]
This should also improve completions performance as the editor has to send `didChange` before requesting completions. 👍

**Comment by neilvyas** [comment]
do we want time-based debouncing? I thought we could just scan the content change for a newline and only run logic based on that. But debouncing is fine by me as well.
