### ISSUE TITLE
pyls doesn't honor the user config file of pycodestyle

### ISSUE THREAD

**Issue by randy3k** [palantir/python-language-server#109]
`pycodestyle` should load a user config file at `~/.config/pycodestyle`
https://pycodestyle.readthedocs.io/en/latest/intro.html#configuration

however, it doesn't seem that pyls honor those settings.

**Comment by gatesn** [comment]
A better solution in fact might be to use the built-in function: https://github.com/PyCQA/pycodestyle/blob/a46c7a6c31773950f5e015a7eb5883f44a8e11de/pycodestyle.py#L2183

**Comment by randy3k** [comment]
I reckoned that, so much work for me though.

**Comment by gatesn** [comment]
Ah ha yes, I've approved your PR so we can merge that, then maybe refactor later
