### ISSUE TITLE
Severity of linting erros

### ISSUE THREAD

**Issue by DerWeh** [palantir/python-language-server#120]
I currently really dislike the displayed errors of the linters.
If I use `pycodestyle` and `Pyflakes` I would prefer that `pycodestyle`s errors like `line too long`, `missing whitespace` could be *downgraded* to warnings or info. Obviously `Pyflakes` messages are more severe, but I still would like `pycodestyles` as an information. 

I hope it can be understood what I mean. Is there a way to configure `pyls` this way?

**Comment by gatesn** [comment]
Thanks for the feedback, I agree they're a little aggressive. Perhaps we bump down all of pycodestyle diagnostics by a level?

I've been working on a PR to making configuring the language server a little easier, so once that merges I'll make this configurable.

________________________________

**Comment by DerWeh** [comment]
Yes sounds like a good solution to me.
