### ISSUE TITLE
Exception on shutdown

### ISSUE THREAD

**Issue by mniewrzal** [palantir/python-language-server#122]
When I'm sending `shutdown` request server throws an exception.

Server version: python-language-server-0.4.2
Request:
`
{
  "jsonrpc": "2.0",
  "id": "3",
  "method": "shutdown"
}
`
Exception:
`
2017-09-04 11:53:50,208 UTC - ERROR - pyls.server - Language server shutting down for uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyls/server.py", line 31, in handle
    self._write_message(response.data)
  File "/usr/lib/python2.7/site-packages/pyls/server.py", line 86, in _write_message
    self.wfile.write(response.encode('utf-8'))
ValueError: I/O operation on closed file
`

**Comment by gatesn** [comment]
@mniewrzal does #123 solve this for you?

**Comment by mniewrzal** [comment]
I reinstalled `pyls` and now I have version 0.5.0 but problem still exists. I'm using pip installation and I'm not 100% sure that patch #123 is included in my version.

**Comment by gatesn** [comment]
Yes, #123 has not merged yet. If you could git clone, checkout the branch for that PR, then pip install the directory, you should be able to test

________________________________

**Comment by mniewrzal** [comment]
Ok, I can try.

**Comment by mniewrzal** [comment]
Works ok with your patch. Thanks :+1:
