### ISSUE TITLE
Completion candidates from activated virtual env

### ISSUE THREAD

**Issue by nicodebo** [palantir/python-language-server#126]
Hi,

I'm working on per project virtual env and the completion menu is not populated with objects from the virtual env modules. For exemple, if `pandas` is installed inside a virtual env, and then `import pan<Tab>` (with <Tab> being the key to trigger the completion menu), I get `pattern not found` from my text editor client (neovim).

Then I have tried to look at the pyls code and I came up with the following patch:

```diff
diff --git a/pyls/workspace.py b/pyls/workspace.py
index caf4124..f0e54ae 100644
--- a/pyls/workspace.py
+++ b/pyls/workspace.py
@@ -80,7 +80,13 @@ class Workspace(object):
         """
         files = config.find_parents(self._root_path, path, ['setup.py']) or []
         path = [os.path.dirname(setup_py) for setup_py in files]
-        path.extend(sys.path)
+        try:
+            venv = os.environ['VIRTUAL_ENV']
+        except KeyError:
+            path.extend(sys.path)
+        else:
+            venv_sys_path = jedi.evaluate.sys_path.get_venv_path(venv)
+            path.extend(venv_sys_path)
         return path
```

Now, the `pandas` candidate appears in the completion menu.
I'm not sure if my fix is correct or If I missed something obvious when working with virtual env, so I prefer to keep it as an issue instead of a pull request.

**Comment by gatesn** [comment]
Your fix does look correct, thanks! I'm just wondering if we should present this as a plugin hook (extending the sys path).

I'm sure some conda users will be wanting the env next.
