### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by yonist** [palantir/python-language-server#135]
Hi, 
Can you share some JSON/RPC calls for testing from the command line? 

I would like to run the server in interactive mode (i.e. reading input from stdio) can you share example for JSON calls for initializing the server ?

Thanks

**Comment by gatesn** [comment]
@yonist the JSON RPC calls you need to initialise the server are all documented here: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

If you want more concrete examples, you should be able to use any of the language clients (e.g. Sublime, VSCode, Atom) and modify the Python command from this `['pyls']`, to something like this `['bash', '-c', 'tee /tmp/pyls_input | pyls -v | tee /tmp/pyls_output']` and you'll be able to see exactly whats getting sent to / received from the server.
