### ISSUE TITLE
installation failed no module versioneer

### ISSUE THREAD

**Issue by cyanotrix** [palantir/python-language-server#137]
I tried installing pyls using the command `pip install python-language-server` and it's giving me this error ever after installing the module versioneer

`$ pip install --user python-language-server --no-cache-dir
Collecting python-language-server
  Downloading python-language-server-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\m1021321\AppData\Local\Temp\pip-build-fuz53dxz\python-language-server\setup.py", line 3, in <module>
        import versioneer
    ModuleNotFoundError: No module named 'versioneer'`

**Comment by cyanotrix** [comment]
I figured the source of the first problem and fixed it. But the second problem seems genuine if I try to install pylp after installing versioneer it says

` AttributeError: module 'versioneer' has no attribute 'get_version'`

Because of which I'm unable to use ide-python in atom. Can someone help? I'm quite new to Python.

**Comment by cyanotrix** [comment]
figured out it was an issue with the `future `package pylp was trying to install.

**Comment by gatesn** [comment]
@cyanotrix do we need to set tighter bounds on our future dependency?

**Comment by cyanotrix** [comment]
@gatesn Probably yes. Because as far as I remember I seem to have edited the package as a workaround and installed it manually. It had caused quite some issue while installing.
