### ISSUE TITLE
Disable plugins

### ISSUE THREAD

**Issue by espositofulvio** [palantir/python-language-server#139]
I am using ST3 with the LSP plugin and python-language-server, it works great most out of the box but I'd like to disable pycodestyle as I don't follow pep8 in so many aspects. I sifted through the issues and found one who seemed to imply something like that is supported, I just can't find any example on how to do so.
Cheers.

**Comment by gatesn** [comment]
So every plugin can be disabled using a config flag like this one: https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L63

@tomv564 might know better, but I think with ST3 you can set these properties with https://lsp.readthedocs.io/en/latest/#per-project-overrides

**Comment by espositofulvio** [comment]
Great, thanks! I managed to get it to work. I also figure out I needed to install the server in my virtualenv, and replace the path to that in config, the VIRTUAL_ENV variable isn't set anywhere, not even using the virtualenv plugin for ST, so I needed something like the following:

```json
{
	"folders":
	[
		{
			"folder_exclude_patterns":
			[
				".env",
				".venv",
				".*cache",
				".hg",
				".egg-info",
				"__pycache__"
			],
			"path": "."
		}
	],
	"virtualenv": "D:\\Work\\Projects\\Catalysis\\.env",
	"settings": 
	{
		"LSP": 
		{
			"pyls":
			{
		        "command": ["D:\\Work\\Projects\\Catalysis\\.env\\Scripts\\pyls"],
		        "scopes": ["source.python"],
		        "syntaxes": ["Packages/Python/Python.sublime-syntax"],
		        "languageId": "python",
		        "settings": {
		        	"pyls": { "plugins": { "pycodestyle": { "enabled": false } } }
		        }
		    }
		}
	}
}
```

Thank you very much for the help
