### ISSUE TITLE
activeParameter in response to textDocument/signatureHelp is sitting in the wrong dict

### ISSUE THREAD

**Issue by rwols** [palantir/python-language-server#141]
https://github.com/palantir/python-language-server/blob/495344c2e15baceec87b547000499b111bdc3664/pyls/plugins/signature.py#L31-L33

the `activeParameter` is now part of the signature dict, while it should be sitting next to the `activeSignature`.

See: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#signature-help-request

**Comment by rwols** [comment]
Simple fix: change `sig['activeParameter'] = s.index` into `sig_info['activeParameter'] = s.index`

**Comment by gatesn** [comment]
Thank you very much for filing this, and thank you for the fix as well! This is addressed in #142
