### ISSUE TITLE
Passing python virtualenv path in config

### ISSUE THREAD

**Issue by espositofulvio** [palantir/python-language-server#143]
Is it possible to specify the virtualenv in the config? I don't know about VSCode but SublimeText doesn't set the VIRTUAL_ENV envvar (even using the VirtualEnv plugin) and thus Jedi can't actually give the right completion suggestions unless the server is installed in the virtualenv and started from there (like I'm doing currently, but I'd like not to install it in each virtualenv for every project I have).

**Comment by gatesn** [comment]
You shouldn’t have to install the server in each virtual env. But I think you would have to launch the editor/IDE from a terminal that had activated the env. Alternatively, the virtual env plugin for the editor should restart language servers “inside” the virtual env.

Those would be the cleanest, however a config option doesn’t sound insane as an override.

________________________________

**Comment by espositofulvio** [comment]
It looks like others have the very same problem: https://github.com/tomv564/LSP/issues/128
In Windows is unusual to start a program from a terminal, so I guess having a config option to set the interpreter path would be the best solution, even though I'm doing exactly that at the moment.
Thanks anyway ;)

**Comment by tomv564** [comment]
@espositofulvio as per https://github.com/tomv564/LSP/pull/133 there is support for setting environment variables for a language server process in `LSP.sublime-settings`.

You would have to install the package from master or wait for the next release to try it.
