### ISSUE TITLE
Custom pycodestyle configuration via xcode/Atom settings

### ISSUE THREAD

**Issue by lgeiger** [palantir/python-language-server#144]
It would be really great to configure the ignored error codes and the maximum line length of `pycodestyle` via the settings if no configuration file is found on the system.

This is the most requested issue on the Atom package for `pyls`: https://github.com/lgeiger/ide-python/issues/9

**Comment by gatesn** [comment]
Happy to add this. But the preferred way would be to add a config option to your global pycodestlye config file: https://github.com/PyCQA/pycodestyle/blob/master/pycodestyle.py#L88
