### ISSUE TITLE
Add didChangeConfiguration Interface

### ISSUE THREAD

**Issue by deathaxe** [palantir/python-language-server#145]
The language-server-protocol defines the `didChangeConfiguration` message to pass configuration data from a client to the language server.

sample server: https://code.visualstudio.com/docs/extensions/example-language-server

The protocol specifies a settings object to be sent to the server:

Example:
```
"settings": {
    "python.sys_path": "/opt/sublime_text_3",
    "pydocstyle.line_length": 100,
}
```

Each editor/client may provide its own strategy to present settings to a user, which may be equally designed for each of several supported language-servers. It is hard for such a client to implement strategies to read/write configuration files for each server in different ways, which would also break the idea of a standard interface for providing language-features.

Therefore I'd suggest/request to implement the `didChangeConfiguration` interface in pyls and clearly define and document a set of configurations supported by the server.

This may include the requirement to create an interface for all pyls plugins to be able to extend the set of valid settings and to hook to the configuration object of a workspace.

This request would be the base to accomplish requests like #144.

Another more general reason for this request are configurations which are not yet part of any existing configuration file, such as extending the `PYTHONPATH` / `sys.path` environment variable on a per workspace base. This is required for Jedi to provide completions for custom/local libraries, which are neither part of python's standard search path or the project file tree.

At the moment pyls uses the `sys.path` of the python interpreter it runs on. Some applications such as Sublime Text use their own python interpreter, which uses different search paths and even different standard libraries, which pyls/Jedi provides possibly wrong completions today but at least misses completions for the Sublime Text libraries.

This request is a result of a discussion about possible solutions to extend Jedi's `sys.path` to find Sublime Text libraries at https://github.com/tomv564/LSP/issues/128

**Comment by tomv564** [comment]
This is already implemented:
https://github.com/palantir/python-language-server/blob/f941b5531500f385fe6a1cfa6333d89e7eac82bf/pyls/python_ls.py#L151

And can already be used to selectively enable plugins (see issue https://github.com/palantir/python-language-server/issues/139 , even has a Sublime/LSP example)

**Comment by deathaxe** [comment]
Searched for `didChange`, so missed it. If it's already there, very fine. One question about it.

The next line ...

https://github.com/palantir/python-language-server/blob/f941b5531500f385fe6a1cfa6333d89e7eac82bf/pyls/python_ls.py#L152

... queries a `pyls` from `settings`. Does it mean all LSP settings in ST need to be wrapped any further into an `pyls` object? What kind of object is `settings`? Is it the directly passed message parameter, which is named as `configParams` in LSP or is it already its `settings` child object?

**Comment by gatesn** [comment]
@deathaxe it's like this:
```
{
  "method": "workspace/didChangeConfiguration",
  "params": {
    "settings": {
      "pyls": {
         "<plugin_name>": {...}
      }
    }
  }
}
```

A reference of supported options is listed here: https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L19

I will keep this up to date as more options are added since as you say, there's not an obvious central place to define these.

**Comment by gatesn** [comment]
If there are configuration options you want, please create individual tickets for them (e.g. the sys.path)
