### ISSUE TITLE
Reliable content for CompletionItem details field

### ISSUE THREAD

**Issue by tomv564** [palantir/python-language-server#149]
In https://github.com/tomv564/LSP/pull/136 a user has decided they do not want to see the CompletionItem `details` because the content is unpredictable and most of the time repeats the `label` field's content:

![screenshot](https://user-images.githubusercontent.com/16542113/31048209-1179a0c2-a619-11e7-9a8e-7e53bacc39cc.png)

PyCharm elects to show the completion's module name in the 2nd column:

<img width="457" alt="screen shot 2017-10-01 at 09 47 06" src="https://user-images.githubusercontent.com/4395832/31052753-edc10fba-a68d-11e7-82a7-09eb7b6c3e9c.png">

The protocol suggests the following about the content of the `detail` field:
```typescript
/**
 * A human-readable string with additional information
 * about this item, like type or symbol information.
 */
detail?: string;
```

The Sublime LSP package will likely provide an option to always display "kind" instead of "detail". 

Jedi's CompletionItem exposes a `module_name` field from BaseDefinition.
Some `python-language-server` users may prefer this content in the "detail" field. 
What do you think?

**Comment by tomv564** [comment]
`module_name` was a bad guess, what I really wanted was the **parent** of the definition.

Using `parent().full_name` gets pretty close:

<img width="320" alt="screen shot 2017-10-01 at 20 32 14" src="https://user-images.githubusercontent.com/4395832/31057712-ac475a80-a6e7-11e7-893b-328067dbf37e.png">

We can also add parameters to the completion labels of functions and methods:

<img width="658" alt="screen shot 2017-10-01 at 20 30 42" src="https://user-images.githubusercontent.com/4395832/31057691-7230942e-a6e7-11e7-877f-bcd597dd8495.png">

That said, we're not trying to turn the language server into a PyCharm engine, so I'd love to hear what other users think. Iterating through Jedi definition's parameters probably has a cost as well.

**Comment by gatesn** [comment]
Agree the current details aren't great. I like the `parent().full_name`, wonder if there's anything cheaper as you say.

Jedi Vim uses the type + full module path:

![screenshot_complete](https://user-images.githubusercontent.com/1928052/31143858-a997aaa2-a876-11e7-9fa2-612f4b1c9cdf.png)

VSCode uses a combination of signature and first line of docs: https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/providers/completionProvider.ts#L27

<img width="591" alt="screen shot 2017-10-03 at 20 12 01" src="https://user-images.githubusercontent.com/1928052/31143995-29556c20-a877-11e7-82e6-20c29555981a.png">

Thoughts on either of these as alternatives?

**Comment by gatesn** [comment]
After clicking that little "i": 

<img width="909" alt="screen shot 2017-10-03 at 20 12 48" src="https://user-images.githubusercontent.com/1928052/31144029-432a18a8-a877-11e7-8c27-b6bd149ce269.png">

**Comment by tomv564** [comment]
From the protocol perspective, it would be ideal to not mix different sources of information into the `detail` field so that the editor/user could configure the completion hint to contain kind, signature or documentation.

I like Jedi Vim's choice here too.
Would "first line of documentation" be reliable / performant?

I'm thinking of doing some benchmarking, and if we have more than one good alternative for `details` then a setting could permit some user preference?

**Comment by deathaxe** [comment]
1. Sublime Text always shows the "detail". Therefore the current solution mostly duplicates the label as follows.

```
sublime     module sublime
debug       def debug
```

2. I like the idea of showing the arguments in the label or would at least find it useful to have the `()` suffixed.



3. The completion kind is already supplied in a dedicated variable and therefore should not be mixed into details.
4. The full docstring of each completion is already supplied via "documentation" variable and may include the whole signature of a function and the first line. It's not used by ST at the moment, but could/should be to display additional info for the selected completion in the future.

Module docstrings may not contain a dedicated first line to be used for details.

The vim solution is not too bad but the mixture of "kind" and the "path" including the function name feels duplicated. I am with @tomv564 not to mix "detail" and "kind" as the later one is displayed as icon in VS Code and may be in ST in the future.

Adding the containing parent module path would probably result in the highest value.

```
lower()         __builtin__.str
is_visible()    sublime.View
sublime         module
import         __builtin__
```

The question is what to display for keywords and top-level imports?

The double underscore looks a bit strange in this context.

**Comment by tomv564** [comment]
I created https://github.com/palantir/python-language-server/pull/170 as I didn't have more time to research, perhaps others can evaluate performance and how the display choices work out in other LSP clients.

**Comment by gatesn** [comment]
Closing this since #170 is merged
