### ISSUE TITLE
pyls installation

### ISSUE THREAD

**Issue by JustMaris** [palantir/python-language-server#160]
When i try to install pyls using "pip install python-language-server" it shows that the installation is complete, but if I write "pyls" in terminal, it shows that there is no command "pyls".
I'm on Ubuntu Mate 17.04

**Comment by YouchaM** [comment]
+1
Mac OsX

**Comment by gatesn** [comment]
I'm not having a problem on OSX, what version of Python are you running? `python -V`

**Comment by extraymond** [comment]
+1 ubuntu 16.04

**Comment by duikboot** [comment]
Doesn't work in Fedora 26 either.
```
[ENV]$ python -V
Python 3.6.2
```
```
[ENV]$ pip freeze                          
astroid==1.5.3
autopep8==1.3.3
configparser==3.5.0
flake8==3.5.0
future==0.16.0
greenlet==0.4.12
isort==4.2.15
jedi==0.11.0
json-rpc==1.10.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
msgpack-python==0.4.8
neovim==0.1.13
parso==0.1.0
pluggy==0.5.2
pycodestyle==2.3.1
pydocstyle==2.1.1
pyflakes==1.6.0
pylint==1.7.4
pylint-django==0.7.2
pylint-plugin-utils==0.2.6
python-language-server==0.9.0
six==1.11.0
snowballstemmer==1.2.1
typing==3.6.2
wrapt==1.10.11
yapf==0.19.0
```

**Comment by gatesn** [comment]
Can you try `pip install --upgrade python-language-server`

**Comment by duikboot** [comment]
> Can you try pip install --upgrade python-language-server

Doesn't work, all the packages are the latest available. 
python-language-server==0.9.0

If I checkout this repo, and install it.
`pip install .`
It doesn't work either.
`python-language-server==0.9.0+3.g9a3545d`

**Comment by JustMaris** [comment]
Python version 2.7.14, still, even after using "pip install --upgrade python-language-server" if I run pyls --help command, it says that there is no such command available.

**Comment by gatesn** [comment]
Hmm, and if you run `pip install pycodestyle` you can run the `pycodestyle --help` command?

**Comment by gatesn** [comment]
Or perhaps try installing it into your user site: `pip install --user python-language-server` after uninstalling it first.

**Comment by JustMaris** [comment]
If i run pip install pycodestyle and run pycodestyle --help
"The program 'pycodestyle' is currently not installed. You can install it by typing:
sudo apt install pycodestyle"

**Comment by duikboot** [comment]
> pip install --user python-language-server

This works, but I prefer it to be installed in a virtualenv dedicated for neovim

**Comment by gatesn** [comment]
Ok, but it suggests it's not python-language-server that's broken here and instead something to do with the PATH. You didn't mention you were trying to install into a virtualenv. What does `which pip` return?

**Comment by duikboot** [comment]
```
$ which pip
~/config/dotfiles/_neovim/ENV/bin/pip
```
It is a python3.6 virtualenv, python-language-server is installed, but there is not an entry created for pyls.

```
[ENV]$ ll ENV/bin 
total 76K
-rw-r--r--. 1 arjen arjen 2.2K Aug 20 16:45 activate
-rw-r--r--. 1 arjen arjen 1.3K Aug 20 16:45 activate.csh
-rw-r--r--. 1 arjen arjen 2.4K Aug 20 16:45 activate.fish
-rwxrwxr-x  1 arjen arjen  246 Aug 20 16:46 autopep8
-rwxrwxr-x. 1 arjen arjen  269 Aug 20 16:45 easy_install
-rwxrwxr-x. 1 arjen arjen  269 Aug 20 16:45 easy_install-3.6
-rwxrwxr-x  1 arjen arjen  258 Oct 17 11:58 epylint
-rwxrwxr-x  1 arjen arjen  253 Oct 29 11:51 flake8
-rwxrwxr-x. 1 arjen arjen  248 Aug 20 16:46 isort
-rwxrwxr-x. 1 arjen arjen  241 Aug 20 16:45 pip
-rwxrwxr-x. 1 arjen arjen  241 Aug 20 16:45 pip3
-rwxrwxr-x. 1 arjen arjen  241 Aug 20 16:45 pip3.6
-rwxrwxr-x. 1 arjen arjen  251 Aug 20 16:46 pycodestyle
-rwxrwxr-x  1 arjen arjen  252 Oct 29 11:51 pydocstyle
-rwxrwxr-x  1 arjen arjen  250 Oct 17 11:58 pyflakes
-rwxrwxr-x  1 arjen arjen  256 Oct 17 11:58 pylint
-rwxrwxr-x  1 arjen arjen  262 Oct 17 11:58 pyreverse
lrwxrwxrwx. 1 arjen arjen    7 Aug 20 16:45 python -> python3
lrwxrwxrwx. 1 arjen arjen   16 Aug 20 16:45 python3 -> /usr/bin/python3
-rwxrwxr-x  1 arjen arjen  258 Oct 17 11:58 symilar
-rwxrwxr-x  1 arjen arjen  250 Oct 29 11:51 yapf

```

**Comment by JustMaris** [comment]
> $ which pip
/usr/bin/pip

For me installing into user should work, but pip --user didnt change anything.

**Comment by yotamN** [comment]
I had the same problem on both Ubuntu and Solus, the solution for me was to add ~/.local/bin to the path. I don't understand why it isn't there by default

**Comment by JustMaris** [comment]
@yotamN Add that to the path of what?

**Comment by yotamN** [comment]
Add it to the `$PATH` enviorment variable like that:
```
PATH=$PATH:~/.local/bin
```

Before you do this you should probably check that the directory exists and have the executables you need, this is how it looks on my computer:

![screenshot from 2017-10-29 16-43-43](https://user-images.githubusercontent.com/5249239/32144884-60c58054-bcc8-11e7-9f96-1ce948f9d3fc.png)

**Comment by JustMaris** [comment]
Thanks. Now pyls works as a command.

**Comment by gatesn** [comment]
Going to close this out. Looks like the default pip prefix is `~/.local/bin` on some machines, and `/usr/local/bin` on others.
