### ISSUE TITLE
Use fixed whitespaces

### ISSUE THREAD

**Issue by deathaxe** [palantir/python-language-server#162]
The language-server-protocol specifies _[Markdown](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_hover)_ to be used for docstrings. As pyls doesn't provide proper markdown formatted docstrings clients such as [LSP](https://github.com/tomv564/LSP) produce somewhat unreadable output. The most significant issue is the markdown processor to replace normal spaces/tabs by a single one, which breaks indention totally.

A docstring like this

```
    """Move cursor to the beginning of the next changed hunk.

    Arguments:
        git_gutter (GitGutterCommand):
            The main command object, which represents GitGutter.
        kwargs (dict):
            The arguments received from the `run_command`.
            This argument is declared to create a common interface being used
            by the GitGutterCommand object.

    Valid kwargs are:
        count (int):
            The number of calls to jump_func to determine the destination.
            Defaults to 1 if the argument is missing or invalid.
        wrap (bool):
            If False, stop searching for the next hunk at document boundaries,
            continue otherwise. If wrap is None, the 'next_prev_change_wrap'
            setting is used.
    """
```

![screenshot](https://user-images.githubusercontent.com/16542113/31681436-7f140530-b377-11e7-8ac4-059c02bdf67e.png)

The language-server is blamed to be responsible to do proper docstring transformation to make sure it can be handled as ordinary markdown.

The least required transformation to ensure docstrings are rendered well was therefore dropped in https://github.com/tomv564/LSP/pull/176/commits/baf565002240dab611001f56d9a565c4159df39e as it is said to be a pyls edge case, caused by in-proper docstring format.

Would it therefore be reasonable to at least pass Jedi's docstrings through the following function to ensure indention is rendered well?

```python
def preserve_whitespace(contents: str) -> str:
    """Preserve indentation in (non-markdown) ascii docstrings (e.g. pyls)"""
    contents = contents.replace('\t', '\u00A0' * 4)
    contents = contents.replace('  ', '\u00A0' * 2)
    return contents
```

A translation of restructured text to markdown would be nice to have but not crucial in a first step.

**Comment by gatesn** [comment]
Thanks for this detailed issue report. Seems as you say the ideal thing here is to run a full RST -> MD compilation. But that can be quite expensive.

I think you're right we should do the minimal thing to preserve whitespace for now.
