### ISSUE TITLE
Problems with LSP (“couldn’t start pyls, disabling”, SublimeText)

### ISSUE THREAD

**Issue by technoiswatchingyou** [palantir/python-language-server#163]
Hi

So problem is that "pyls" do not starting with Sublime: "couldn't start pyls, disabling". But if i restart server manually (LSP: Restart Servers) everything is ok for opened Sublime session. What can be reason for this? LSP is globally enabled. Recently i installed LSP and everything was fine.

Thanks for help.

MacOS 10.13.1
SublimeText v3.0, buil 3143

**Comment by gatesn** [comment]
@tomv564

**Comment by tomv564** [comment]
Issue is now duplicated in the LSP repo, caused by incomplete PATH at startup in Sublime Text on OS-X (known before: https://github.com/tomv564/LSP/issues/147).
