### ISSUE TITLE
Docs for using with LanguageClient-neovim

### ISSUE THREAD

**Issue by AdrianRibao** [palantir/python-language-server#167]
I'm trying to integrate pyls with https://github.com/autozimu/LanguageClient-neovim

I can't make it work and I didn't find any help on the docs, maybe it could be useful to explain this case in the README or the docs.

My current implementation:

init.vim

```
let g:LanguageClient_serverCommands = {
    \ 'python': ['/usr/local/lib/python2.7/dist-packages/pyls'],
    \ }
```
I've tested also with 

```
let g:LanguageClient_serverCommands = {
    \ 'python': ['/usr/local/lib/python3.6/dist-packages/pyls'],
    \ }
```

but when I try to start the server with :LangualeClientStart it says:

**Failed to start language server: Permission denied**

Is this the right way to do it?

**Comment by gatesn** [comment]
It should just work with

```
let g:LanguageClient_serverCommands = {
    'python': ['pyls', '-v'],  # For some debug logging
}
```

Assuming you've run `pip install python-language-server` and are running neovim from the same environment. If you aren't running in a virtualenv, then it is likely installed at `/usr/local/bin/pyls`. But `/usr/local/bin` should be on your PATH.

**Comment by gatesn** [comment]
Closing this out as its more of a client issue
