### ISSUE TITLE
[Feature Request] More performant server

### ISSUE THREAD

**Issue by HerringtonDarkholme** [palantir/python-language-server#17]
Hi. Python language server is well written, thank you for your contribution.

However, after using I find some improvements can be done.

1. logger 
Tracked by https://github.com/palantir/python-language-server/issues/15. Logging to stderr will block stdout writing.

2. threaded reading
Now PLS in stdio mode is single threaded. https://github.com/palantir/python-language-server/blob/6c781d4012521017e6a84e6d7d49827644ae669e/pyls/language_server.py#L29
So if client sends too many requests than stdin can buffer, PLS will also block because it cannot write to stdout. (It seems stdin/stdout/stderr share one common buffer)

3. cached compeletion
PLS generally is slower than deoplete-jedi, another jedi based completion plugin. The main reason is deoplete-jedi uses a cache. https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py If PLS can also support cache it should be faster.

Thanks!

**Comment by gatesn** [comment]
+1 to all three here!

**Comment by HerringtonDarkholme** [comment]
Hi @gatesn! Thanks for quick reply.

Currently I use PLS with neovim. But I would like to try it out with VSCode like that in README. However I cannot find extension in VSCode market. Would you like provide a installation manual?

Or do I need create a wrapper extension for PLS? Thanks!

**Comment by gatesn** [comment]
@HerringtonDarkholme nice idea. I've noticed a few language servers do come with wrapper extensions. Would be happy to look into it some time, could you create a separate issue for it? Thanks

**Comment by gatesn** [comment]
@HerringtonDarkholme thanks for raising these points. I want to close this ticket and instead track individually any ideas for performance improvements. Here are some to get us started:

https://github.com/palantir/python-language-server/labels/performance
