### ISSUE TITLE
[feature] give possibility to disable pyflakes checks

### ISSUE THREAD

**Issue by tdi** [palantir/python-language-server#185]
Hi
Is this supported ? I would like to disable certain checks for Pyflakes, e.g. E501.

**Comment by gatesn** [comment]
Not right now unfortunately. I'm currently working on refactoring some of the configuration parsing to allow more flexibility here. After this I hope to support configurations for all plugins.

**Comment by tdi** [comment]
Just an idea, maybe use flake8, then it is configurable in ~/.config/flake8
