### ISSUE TITLE
[documentSymbol] Location ranges should span entire definition

### ISSUE THREAD

**Issue by svenefftinge** [palantir/python-language-server#188]
Since the LSP doesn't provide hierarchical symbols, yet, outline tree implementations for Vs Code, Theia and Eclipse are based on location.ranges to compute parent/child relationship based on nesting. This python LS unfortunately only covers the range of the identifier not the full construct, so it doesn't work here. Other LS implementations provide the full range.

See e.g. https://github.com/patrys/vscode-code-outline/blob/master/src/symbolOutline.ts#L97

**Comment by gatesn** [comment]
Can you find a Microsoft implementation of outline view? I'd rather use that as reference for how to interpret something explicitly forbidden in the protocol: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-symbols-request

Some of the comments do hint at the location spanning more than just the identifier name: 

> The location of this symbol. The location's range is used by a tool
    to reveal the location in the editor. If the symbol is selected in the
    tool the range's start information is used to position the cursor. So
    the range usually spwans more then the actual symbol's name and does
    normally include thinks like visibility modifiers.

But then shortly after, inferring hierarchy is disallowed:

> The range doesn't have to denote a node range in the sense of a abstract
    syntax tree. It can therefore not be used to re-construct a hierarchy of
    the symbols.

And this warning is repeated for `containerName`:

> The name of the symbol containing this symbol. This information is for
    user interface purposes (e.g. to render a qaulifier in the user interface
    if necessary). It can't be used to re-infer a hierarchy for the document
    symbols.

**Comment by svenefftinge** [comment]
Yes, see also https://github.com/Microsoft/language-server-protocol/issues/132.
Still, there is no other practical solution atm and using the ranges seems a viable workaround until the mentioned hierarchy information is made available explicitly.

**Comment by gatesn** [comment]
@svenefftinge I can't seem to be able to reproduce this? The ranges PYLS reports (at least now, wonder if Jedi changed?) span the full definition:

<img width="1229" alt="screen shot 2018-03-25 at 09 53 19" src="https://user-images.githubusercontent.com/1928052/37873316-70aa5ce8-3012-11e8-9314-0b889b4b6b16.png">


Please re-open if you're still seeing issues
