### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by mklemm2** [palantir/python-language-server#191]
Hi,

From the ReadMe:

Change the pyls.configurationSources setting to ['flake8'] in order to respect flake8 configuration instead.

But somehow there is no explanation how to actually do this. What's the path to the config file? What format is it?

Ciao, Marcus

**Comment by tomv564** [comment]
This depends on the client, but eg. VS Code expects you to add that setting VS Code's User or Workspace settings.

After VS Code has started python-language-server, it will send it those settings in a `didChangeConfiguration` notification.

You can see the complete list of synced settings here: https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L18-L151

**Comment by gatesn** [comment]
Closing this out. Please re-open if your question has not been answered.

**Comment by martsa1** [comment]
Urm, what about for use with Neovim via a neovim language server?  Should I be looking in the language server's settings to try and set this up?

**Comment by joaqo** [comment]
@gatesn sorry for reviving this thread, but is there a way to do this in Vim + ALE instead of VSCode?
