### ISSUE TITLE
Inconsistent hover popups

### ISSUE THREAD

**Issue by mg979** [palantir/python-language-server#196]
Reposted from here
https://github.com/tomv564/LSP/issues/223

When inside function arguments parentheses, it displays:

![Imgur](https://i.imgur.com/YqPjOb0.png)

When hovering, this instead:

![Imgur](https://i.imgur.com/CWNuZy7.png)

Is it possible to make hover popups display as the first type?

For what I can understand, signature string formatting uses https://github.com/palantir/python-language-server/blob/3c1f18361179f3a687bdef6209e136a10bbf043f/pyls/plugins/signature.py#L9 while hover uses https://github.com/palantir/python-language-server/blob/3c1f18361179f3a687bdef6209e136a10bbf043f/pyls/plugins/hover.py#L9 and that gives a different result? Could the same signature string formatting be used for hover popup too? Thanks

**Comment by gatesn** [comment]
Absolutely, thanks for spotting this!

________________________________

**Comment by mg979** [comment]
Cool, thanks :+1:
