### ISSUE TITLE
ResourceNotFoundError: Resource </main.py> does not exist

### ISSUE THREAD

**Issue by SamVerschueren** [palantir/python-language-server#207]
I receive the following error quite often. I tried to trace down what causes this issue because the error seems to appear at [rope_completion.py#27](https://github.com/palantir/python-language-server/blob/develop/pyls/plugins/rope_completion.py#L27).

```
Python Server: 2017-12-22 09:08:41,938 UTC - ERROR - pyls._utils - Failed to run hook rope_completion
Traceback (most recent call last):
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pyls/_utils.py", line 105, in _apply
    return impl, impl.function(**kwargs)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pyls/plugins/rope_completion.py", line 27, in pyls_completions
    offset, document._rope, maxfixes=3)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pyls/workspace.py", line 175, in _rope
    return libutils.path_to_resource(self._rope_project, self.path)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/rope/base/libutils.py", line 27, in path_to_resource
    return project.get_resource(project_path)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/rope/base/project.py", line 331, in get_resource
    return super(NoProject, self).get_resource(universal_name)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/rope/base/project.py", line 42, in get_resource
    'Resource <%s> does not exist' % resource_name)
ResourceNotFoundError: Resource </main.py> does not exist
```

I try to use the language service with the monaco editor. I noticed that the URI of the file is `file:///main.py` for instance, hence the triple slash. Could this be the reason why it fails?

PS. Sorry about opening so much issues, but I really want to get this language service working

**Comment by gatesn** [comment]
No no, please open more issues! It would appear that no one has yet made any use of pydocstyle linting, hence those bugs.

In this case, I believe it's because the workspace root is defaulting to '/' somewhere, and therefore Rope is trying to read your files from the root directory.

**Comment by SamVerschueren** [comment]
Can I do something in order to resolve this or help you with resolving it?

**Comment by SamVerschueren** [comment]
Tried to look into this, but my Python skills are almost non-existing, sorry for that. I was looking right [here](https://github.com/palantir/python-language-server/blob/develop/pyls/workspace.py#L85) in `workspace.py` because it looks like it is setting up the rope project.

I'm just wondering, what value should the `root_path` be? Should it be `/`, should it be empty? I have no idea...

**Comment by gatesn** [comment]
I think the answer might be to disable all rope plugins if the workspace root is None. One day we might be able to figure out a way to get Rope and Jedi to run against in-memory files, but for now they both sort of require things to be on-disk.

**Comment by SamVerschueren** [comment]
So is it possible to have intellisense without having the files on disk? Or what plugin is providing the intellisense part?

**Comment by gatesn** [comment]
So you can have intellisense for the current file, but it won't be aware of any others. e.g. you cannot jump to definition in another file if the files aren't on disk. But you'll still get linting and jump to definition within the file, as provided by Jedi to which we give the current document's source as a string.

**Comment by gatesn** [comment]
I do hope to add better support for null rootUris soon though!

**Comment by gatesn** [comment]
Closing this out for now, please re-open if it's still an issue for you
