### ISSUE TITLE
Handle exeptions from feature provider

### ISSUE THREAD

**Issue by lgeiger** [palantir/python-language-server#214]
Feature providers may throw exceptions which are currently unhandled which may result in a language server crash.

E.g.:
- `yapf` may throw a parsing error https://github.com/lgeiger/ide-python/issues/44#issuecomment-354559034
- `jedi` may throw a "maximum recursion depth" error on hover

I suggest we wrap the calls to external feature providers in `try`/`catch` statements and return a [`ResponseError`](https://microsoft.github.io/language-server-protocol/specification#response-message) if they fail instead of leaving the exception unhandled.

What do you think?

**Comment by gatesn** [comment]
Huh, it's weird that exceptions aren't caught by this line: https://github.com/pavlov99/json-rpc/blob/master/jsonrpc/manager.py#L115

As invoked by https://github.com/palantir/python-language-server/blob/develop/pyls/server.py#L49

**Comment by lgeiger** [comment]
Thanks for the links. I'll investigate

**Comment by ferozco** [comment]
Think this was resolved with #261
