### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type NSException | macOS

### ISSUE THREAD

**Issue by nasyxx** [palantir/python-language-server#217]
I use this for the first time, but it looks like the start is not very smooth, in fact, I can not even open the help.

Please see this log

https://gist.github.com/nasyxx/a1ed307bd219e1af25dbbe349b657e53 

I'm sorry I do not know what to describe ... I just installed it from pip and ran it on the command line.

**Comment by gatesn** [comment]
What’s the result of `which python`?

**Comment by nasyxx** [comment]
```
λ which python
/usr/local/bin/python
```

However, I used `pip3` to install.

```
λ which python3
/usr/local/bin/python3
```

**Comment by nasyxx** [comment]
I think I found the reason, it seems not the pyls problem, but due to skimage. I deleted skimage no problem. Maybe I should give skimage an issue.

**Comment by gatesn** [comment]
Glad you got it sorted

**Comment by fohria** [comment]
I had this issue with python-language-server 0.13.0. Using Anaconda3 (4.4.9) on macos 10.13.3.

I fixed it by telling matplotlib to use TkAgg as backend, like so:

1. Create ~/.matplotlib/matplotlibrc
2. Add "backend: TkAgg" (without the quotations) to the file

Source: https://stackoverflow.com/questions/31373163/anaconda-runtime-error-python-is-not-installed-as-a-framework/44912322#44912322

**Comment by nasyxx** [comment]
@fohria 

Indeed it is the case, this time, even if skimage is installed, have no problem.

Thank you very much!

<img width="412" alt="screen shot 2018-02-13 at 7 55 08 pm" src="https://user-images.githubusercontent.com/5007613/36148735-05fab0d4-10f8-11e8-852d-fb26d4317504.png">

**Comment by raincrash** [comment]
@fohria Thanks! That saved my day.

**Comment by RachelChai123** [comment]
@fohria Thanks!!
