### ISSUE TITLE
Maybe we should prevent creating a .ropeproject/config.py

### ISSUE THREAD

**Issue by segevfiner** [palantir/python-language-server#230]
When you use pyls today, it ends up creating a `.ropeproject/config.py` in any project that you open with it. This might make sense for users who use rope directly, but less so for someone unfamiliar with it, who just tried to use pyls and ends up with a new untracked file in his VCS.

Maybe something should be done to prevent it's creation by pyls? (If at all possible...)

**Comment by exploide** [comment]
I also thought of this and according to the documentation it is possible to suppress folder creation: https://github.com/python-rope/rope/blob/master/docs/library.rst#ropeproject-folder

However, I'm not familiar with rope and do not know what exactly is done with this folder and if it is reasonable to disable it or if it would lead to performance problems or whatever.

**Comment by segevfiner** [comment]
I don't know either. Hence the "maybe" in the title. That's what the
documentation has to say https://github.com/python-rope/rope/blob/master/docs/overview.rst#ropeproject-folder.

It seems it holds configuration, history and caches.

It can always be made configurable rather than outright disabling it...

בתאריך 18 בינו' 2018 16:21,‏ "Jannik Vieten" <notifications@github.com> כתב:

**Comment by evandrocoan** [comment]
This configuration file is extremely annoying. I would never use this tool until this madness is removed. Next thing to do is to find and kill this trash file creation. 

If I would like this damn thing on my project, I can create the damn file myself from a template.

**Comment by segevfiner** [comment]
I guess the first two things that can be done are making the Rope `Project` initialization lazy rather than at the initialization of pyls (I think it's in workspace.py), and adding a configuration value for the location of `.ropeproject` that can also include some replacement variables like `$PROJECT` or `{PROJECT}` etc that can be used to relocate it to a project dependent location outside of the project directory.

I wonder what other projects using Rope do...

**Comment by evandrocoan** [comment]
I am attempting to create a setting on https://github.com/palantir/python-language-server/pull/253 to disable the folder creation. You guys can test and see if it is working correctly for you.

**Comment by mcepl** [comment]
If you disable creating this folder, please, make it optional. There are some fun things I do with ``~/.ropeproject/config.py``, which I would miss.

**Comment by gatesn** [comment]
I believe this PR means you won't get a rope project if it's not installed: https://github.com/palantir/python-language-server/pull/301
