### ISSUE TITLE
Errors are being marked as warnnigs

### ISSUE THREAD

**Issue by evandrocoan** [palantir/python-language-server#235]
Follows from https://github.com/tomv564/LSP/issues/252 Syntax error should be red instead of yellow

Enabling log of payloads we see:
`
LSP:  --> textDocument/didOpen
LSP: <--  textDocument/publishDiagnostics
LSP:      {'uri': 'file:///F:/SublimeText/Data/Packages/PythonDebugTools/tests/manual_tests.py', 'diagnostics': [{'severity': 2, 'message': "undefined name 'sublime_plugin'", 'source': 'pyflakes', 'range': {'end': {'character': 60, 'line': 7}, 'start': {'character': 0, 'line': 7}}}, {'range': {'end': {'character': 1, 'line': 0}, 'start': {'character': 1, 'line': 0}}, 'severity': 2, 'source': 'pydocstyle', 'message': 'D100: Missing docstring in public module', 'code': 'D100'}, {'range': {'end': {'character': 1, 'line': 18}, 'start': {'character': 1, 'line': 18}}, 'severity': 2, 'source': 'pydocstyle', 'message': 'D103: Missing docstring in public function', 'code': 'D103'}]}
`
...
`
{'severity': 2, 'message': "undefined name 'sublime_plugin'", 'source': 'pyflakes', 'range': {'end': {'character': 60, 'line': 7}, 'start': {'character': 0, 'line': 7}}
`

Does `pyflakes` is messing up with severity?

**Comment by gatesn** [comment]
If you check the commit history on the pyflakes linter you’ll see we removed a section from the reporter because some non-errors were being returned as errors.

I guess that change was too general.

________________________________
