### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cosmoscalibur** [palantir/python-language-server#238]
When check if installation was correct using `pyls -h` a `Segmentation fault (core dumped)` error is prompted.  

__Details__:

+   python-language-server 0.13.0  
+   Lubuntu 16.04  
+   python 3.5.2

**Comment by gatesn** [comment]
I haven't been able to reproduce this, and doesn't seem anyone else is hitting this issue so I'm going to close
