### ISSUE TITLE
Rename uses max size Range line number

### ISSUE THREAD

**Issue by siegelaaron94** [palantir/python-language-server#241]
I have been trying to use python-language-server in vim-lsp and have been having issues with rename.
When rename is invoked the server responds with a range with an end location of (sys.maxsize,0). Shouldn't this be (NUMBER_OF_LINES_IN_DOCUMENT, LAST_COLUMN_IN_DOCUMENT)? Here is the relevant code.
https://github.com/palantir/python-language-server/blob/698325d62c2862f6d4c991f2970b6bc744532239/pyls/plugins/rope_rename.py#L35

**Comment by gatesn** [comment]
Fixed in #345
