### ISSUE TITLE
Content-Length should be byte length rather string length

### ISSUE THREAD

**Issue by HerringtonDarkholme** [palantir/python-language-server#25]
Spec:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#header-part

> Content-Length 	number 	The length of the content part in bytes. This header is required.

But implementation is string length.

Read part:

https://github.com/palantir/python-language-server/blob/master/pyls/jsonrpc.py#L136

Write part:
https://github.com/palantir/python-language-server/blob/master/pyls/jsonrpc.py#L147-L148

Write part is more convoluted. json.dumps by default return all ascii character so it is **implicitly** equal to byte length,

**Comment by gatesn** [comment]
Good catch! Once again thank you for raising these issues. 

Apologies for not being very active in the project recently but we've been a little busy on other (related!) projects. We will be revisiting this project very soon to give it a much needed facelift.

**Comment by gatesn** [comment]
Would these be handled better by just using a third-party jsonrpc library? Probably shouldn't be rolling our own.

**Comment by gatesn** [comment]
@HerringtonDarkholme I don't quite see where the error is at the moment? As you say, dumps produces ascii so the length is correct (unless you're saying you want to support writing unicode?) And read takes a byte count as parsed from the content length, which again sounds right? Could you elaborate?

**Comment by HerringtonDarkholme** [comment]
@gatesn  I 'll explain more detail. pyls is wrong in reading client request (but is correct in writing response).

Now, pyls will import `sys.stdin` and `sys.stdout` as reading and writing file. They are `TextIOWrapper` of which the `read` and `write` accept arguments as string length.

However, a well behaved language client will send `Content-Length` as byte length. If the file being edited contains non-ascii character and client does not escape file content to ascii code, the content-length client sent is not the same as the string length of content body.

For example, given a file contains utf-8 only character

```py
 わーい='たのしい'
```

Client can send Request like this:

```json
Content-Length: 38

{"content: "わーい=\'たのしい\'"}
```

pyls will read 38 **characters**, but not 38 bytes!  However, client only send 24 characters.

Language Client Protocol does not specify json body must be encoded in pure ascii. So this client request is legal.

pyls can respond client correctly because json.dumps escapes all unicode to ascii code like `\xABC` so the byte length is the same as string length.

**Comment by gatesn** [comment]
Thank you! That makes much more sense, I was unaware of 'TextIOWrapper of which the read and write accept arguments as string length'.

I will look into a fix for this.
