### ISSUE TITLE
Does is really necessary PythonLanguageServer has an Workspace attribute and vice-versa?

### ISSUE THREAD

**Issue by evandrocoan** [palantir/python-language-server#250]
Currently `PythonLanguageServer` has an `Workspace` attribute and `Workspace` has an `PythonLanguageServer` attribute. Perhaps this can be changed? Is it kinda too [tight](https://stackoverflow.com/questions/2832017/what-is-the-difference-between-loose-coupling-and-tight-coupling-in-the-object-o) coupled?

**Comment by gatesn** [comment]
+1000

________________________________
