### ISSUE TITLE
Server doesn't shutdown in TCP mode

### ISSUE THREAD

**Issue by tomv564** [palantir/python-language-server#255]
I've been testing TCP mode with LSP and pyls has been really valuable. The only feature not working  for me is process shutdown when an `exit` notification is sent.

I think something needs to be done to close the socket server around this code:
https://github.com/palantir/python-language-server/blob/099eb3691b3b90569f473ed920bb6045b06ff561/pyls/language_server.py#L35

For completeness sake it might be worth a look (any ideas?) but I won't be exactly heartbroken if you close this issue as `wontfix` :)

**Comment by gatesn** [comment]
Please re-open if this is still an issue for you
