### ISSUE TITLE
autopep8 plugin?

### ISSUE THREAD

**Issue by max-sixty** [palantir/python-language-server#259]
Would an autopep8 plugin be additive? 

The advantage of autopep8 over yapf is that autopep8 is far more conservative - it only changes code where there's a linting error, and so easier to apply to existing codebases.

Looking through the docs of pyls, I don't _think_ there's an immediate way to use something more conservative than yapf to format code - is that correct?

Thanks

**Comment by max-sixty** [comment]
...and `flake8` would be another, but more driven by a personal preference than it doing anything that the current linters don't

**Comment by gatesn** [comment]
Not possible right now, but definitely worth doing I think.

**Comment by max-sixty** [comment]
> Not possible right now

Not possible for you to work on, or not possible for someone else to PR this?

**Comment by gatesn** [comment]
Not possible given there’s no autopep8 plugin. It’s not top of my list, so if it’s urgent I would be happy to look at PRs. Should be quite similar to YAPF.

**Comment by max-sixty** [comment]
OK great! I haven't looked at the library but would be keen to contribute
