### ISSUE TITLE
Crash for completions for Python 3.4

### ISSUE THREAD

**Issue by danielnowakowski** [palantir/python-language-server#282]
Pyls crashes for completions for Python 3.4.3.

Let's consider the following example:
```
import os
import pickle

os.pathsep
pickle.
```

and request for completions after the last dot. I expect to have a list of elements available in pickle module. However, pyls crashes.

Log is following:
`2018-03-02 13:45:04,458 UTC - DEBUG - pyls.server - Got message: b'{"jsonrpc":"2.0","id":46,"method":"textDocument/completion","params":{"textDocument":{"uri":"FILE_URI"},"position":{"line":4,"character":7}}}'`

`2018-03-02 13:45:04,458 UTC - DEBUG - pyls.config.config -   pyls_completions [hook]
      workspace: <pyls.workspace.Workspace object at ADDRESS>
      document: FILE_URI
      config: <pyls.config.config.Config object at ADDRESS>
      position: {'character': 7, 'line': 4}`

Process finishes simply without any additional errors.

Everything works as expected for Python 3.6.

**Comment by ferozco** [comment]
what version of pyls are you using?

**Comment by danielnowakowski** [comment]
Version 0.14.0

**Comment by gatesn** [comment]
I cannot reproduce this with PYLS 0.16.0 and Python 3.4.6. Is this still an issue for you? If so could you re-open the ticket having run pyls in debug mode `pyls -vvv`
