### ISSUE TITLE
Make plugins "more optional"

### ISSUE THREAD

**Issue by gatesn** [palantir/python-language-server#299]
Right now, although it's possible to turn off various plugins (e.g. pydocstyle, rope completions etc.) the pydocstyle and rope dependencies are still required.

We should move towards having all plugins optional, beyond Jedi, and therefore only used if they are installed. This would require the module imports to be moved within plugin scopes, and probably some runtime version checks, e.g. ensure that pyflakes is >= 1.6.0 at runtime, else loudly print out a warning.

**Comment by wmonk** [comment]
Can a requirement of this feature be to be able to turn them off from the cli?

**Comment by gatesn** [comment]
@wmonk can we track that here? https://github.com/palantir/python-language-server/issues/300
