### ISSUE TITLE
README: Consider migrating .rst -> .md

### ISSUE THREAD

**Issue by rootulp** [palantir/python-language-server#3]
- Markdown has less overhead for people who want to contribute directly from GitHub (no build step / rich diffs)
- Most Palantir open source projects use markdown for their READMEs (exception: [typedjsonrpc](https://github.com/palantir/typedjsonrpc))

I'm happy to do the conversion if you think this makes sense @gatesn

**Comment by gatesn** [comment]
Almost all Python projects use RST instead of MD. I think PyPi has only recently started supporting Markdown which is part of the reason for this.

I seem to get pretty good diffs editing the readme from Github?

**Comment by rootulp** [comment]
Whoops! I didn't realize Github READMEs support `.rst` files in Preview Changes. I think this can be closed.
