### ISSUE TITLE
conflict with futures 3.2.0

### ISSUE THREAD

**Issue by changephilip** [palantir/python-language-server#351]
I use python3.5 on Debian.
new futures 3.2.0 is no longer supported on python3.5, 
so after installing pysl , lsp-python-stderr reports that the package "futures" can't be imported. 
I find futures 3.1.1 still work.
It may be useful for other Debian users.

**Comment by w0rp** [comment]
I see the same issue myself. If I install python-language-server into a Python 3.6 virtualenv environment, it doesn't run due to this error.

```
pkg_resources.DistributionNotFound: The 'futures' distribution was not found and is required by the application
```

Maybe it should try looking for the first party `concurrent.futures` module first, and fall back on the `futures` library if that can't be found.

**Comment by w0rp** [comment]
This works as a workaround for me.

```bash
pip install futures==3.0.0
pip install python-language-server==0.17.0
```

**Comment by gatesn** [comment]
What version of setuptools do you have installed? `pip list`

**Comment by w0rp** [comment]
I'm back at the machine I last tried this on now. I had `setuptools (32.3.1)`, and `pip 9.0.3`. I know that at work, we had an issue with upgrading to pip 10, for now.

**Comment by gatesn** [comment]
@w0rp it seems like something isn't respecting our install_requires block since we exclude futures when Python is less than 3.2. If you uninstall both futures and python-language-server, then install python-language-server does it still try to install futures?

**Comment by w0rp** [comment]
With that pip version, it does try to install `futures`.

```
$ python3.6 --version
Python 3.6.3
```

If you follow the steps with noise from output removed...

```
$ python3.6 -m venv ve
$ ve/bin/pip install pip==9.0.3
$ ve/bin/pip install python-language-server
$ ve/bin/pip freeze | grep futures
futures==3.1.1
```

It does the same with the latest pip too, if you use `ve/bin/pip install -U pip`. In a blank virtual environment, it will install it okay.
