### ISSUE TITLE
Fork our pyls.jsonrpc to as an indepenedent module

### ISSUE THREAD

**Issue by ksdme** [palantir/python-language-server#352]
The internal jsonrpc module pyls currently uses is also being used by https://github.com/coala/coala-vs-code and I also plan to use it while developing a coala language server. Do you think it would be possible to fork the module out as an independent module? I would be glad to help.

**Comment by gatesn** [comment]
Do you think it's worth forking the jsonrpc server along? Or fork a language server implementation, that then Python and Coala could both implement?

**Comment by ksdme** [comment]
I do not think we require a server. The core use case for this suggested fork is for is coala language server to be able to use it too. I would prefer if the jsonrpc module stayed protocol independent and provided a method and request dispatch mechanism and some stream handling. I think this would require least amount of work as most of the implementation has already been done for pyls.

Do you think this is possible?

**Comment by gatesn** [comment]
Yup, I agree that the jsonrpc module is useful by itself. I'll start the process to fork this out

**Comment by ksdme** [comment]
Thank you very much. Please let me know if I can help during the process.

**Comment by gatesn** [comment]
https://github.com/palantir/python-jsonrpc-server
