### ISSUE TITLE
KeyError 'pycodestyle'

### ISSUE THREAD

**Issue by purpleP** [palantir/python-language-server#354]
With my configuration I have `KeyError 'pycodestyle'` when pyls initializes configs.

I've fixed it by adding this

`/home/michael/.venv/lib/python3.6/site-packages/pyls/config/config.py:94`

```
        for source_name in reversed(sources):
            source = self._config_sources.get(source_name)
            if not source:
                continue
```
I can make a pull request If you someone explains to me how configuration works in language servers. I don't understand for example where should main lsp configbe. Should it be in `~/.settings.json` or in `~/settings.json` or somewhere in `~/.config`?

**Comment by gatesn** [comment]
Fixed in #355
