### ISSUE TITLE
Start the language-server from the command line

### ISSUE THREAD

**Issue by ftomassetti** [palantir/python-language-server#36]
Hi, I would like to integrate your server in an editor I am working on (https://github.com/ftomassetti/kanvas).

My first naive attempt was to run:

```
python pyls/language_server.py
```

in a virtualenv.

That does not work:

```
Traceback (most recent call last):
  File "pyls/language_server.py", line 4, in <module>
    from .server import JSONRPCServer
ValueError: Attempted relative import in non-package
```

I am probably doing something blatantly wrong. What is the best way to just start the server?

**Comment by gatesn** [comment]
You should be able to 'pip install .' Inside the checked out repo and then run 'pyls' as it will now be installed on your path.

**Comment by gatesn** [comment]
Let me know if this doesn't work for you
