### ISSUE TITLE
Error when running pip install: python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by schalkneethling** [palantir/python-language-server#370]
Have tries a couple of times now, but each time the result is the same:

```
pip install python-language-server
Collecting python-language-server
  Downloading https://files.pythonhosted.org/packages/97/4c/b561716780888f8df9ed44b5e2b8b499258c31b7722d96da0002483fcdd2/python-language-server-0.19.0.tar.gz (55kB)
    100% |████████████████████████████████| 61kB 150kB/s
    Complete output from command python setup.py egg_info:
    error in python-language-server setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in configparser; python_version<"3.0" at ; python_version<"3.0"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-install-5Zy4C7/python-language-server/
```

Not sure if it is an XCode thing or perhaps the version of Python.

OS: macOS High Sierra v10.13.4
Python: 2.7.10

**Comment by gatesn** [comment]
Please update setup tools `pip install -U setuptools`

**Comment by schalkneethling** [comment]
Oh ow, that is causing an even bigger error :-/

```
pip install -U setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl (567kB)
    100% |████████████████████████████████| 573kB 635kB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 18.5
    Uninstalling setuptools-18.5:
Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/private/var/folders/l1/mjqxjq7j08jb6z6_f7j5wcgw0000gn/T/pip-uninstall-HGTmWv/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
```

Any suggestions? Thanks a lot

**Comment by schalkneethling** [comment]
Hmmm, tried `sudo` and `sudo -H` but pretty much the same:

```
sudo -H pip install -U setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl (567kB)
    100% |████████████████████████████████| 573kB 463kB/s
matplotlib 1.3.1 requires tornado, which is not installed.
Installing collected packages: setuptools
  Found existing installation: setuptools 18.5
    Uninstalling setuptools-18.5:
Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-3xJsCH/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
```

**Comment by gatesn** [comment]
Can you try `brew install python` instead of use the Mac’s native one? There are some issues with it it would seem.

**Comment by schalkneethling** [comment]
@gatesn Did this previously, so I did `brew reinstall python`

Here is the output of that:

```
==> Reinstalling python
==> Installing dependencies for python: sqlite
==> Installing python dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.24.0.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a5/a51a1d0a22f6648b41980363dae433223785b55cf62bd9c67a78c15eadad7a99?__gda__=ex
######################################################################## 100.0%
==> Pouring sqlite-3.24.0.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

==> Summary
🍺  /usr/local/Cellar/sqlite/3.24.0: 11 files, 3.5MB
==> Installing python
==> Downloading https://homebrew.bintray.com/bottles/python-3.6.5.high_sierra.bottle.1.tar.gz
Already downloaded: /Users/schalkneethling/Library/Caches/Homebrew/python-3.6.5.high_sierra.bottle.1.tar.gz
==> Pouring python-3.6.5.high_sierra.bottle.1.tar.gz
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/loca
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/loca
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/loca
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

Pip, setuptools, and wheel have been installed. To update them run
  pip3 install --upgrade pip setuptools wheel

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.6/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
```

The did `echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.zshrc`

Then did: `pip3 install --upgrade pip setuptools wheel` and got

```
Cache entry deserialization failed, entry ignored
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages (10.0.1)
Cache entry deserialization failed, entry ignored
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl
Cache entry deserialization failed, entry ignored
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl
Installing collected packages: setuptools, wheel
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
  Found existing installation: wheel 0.31.0
    Uninstalling wheel-0.31.0:
      Successfully uninstalled wheel-0.31.0
  Rolling back uninstall of wheel
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/bin/wheel'
Consider using the `--user` option or check the permissions.
```

So I did: `sudo pip3 install --upgrade pip setuptools wheel` and got

The directory '/Users/schalkneethling/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/schalkneethling/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages (10.0.1)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.6/site-packages (39.2.0)
Requirement already up-to-date: wheel in /usr/local/lib/python3.6/site-packages (0.31.1)

Then did `sudo pip3 install python-language-server`

And it seems to have worked:

```
The directory '/Users/schalkneethling/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/schalkneethling/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python-language-server
  Downloading https://files.pythonhosted.org/packages/97/4c/b561716780888f8df9ed44b5e2b8b499258c31b7722d96da0002483fcdd2/python-language-server-0.19.0.tar.gz (55kB)
    100% |████████████████████████████████| 61kB 1.1MB/s
Collecting future>=0.14.0 (from python-language-server)
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 3.3MB/s
Collecting jedi>=0.12 (from python-language-server)
  Downloading https://files.pythonhosted.org/packages/e7/42/074192a165622e645ed4aeade63e76e56b3496a044569b3c6cae3a918352/jedi-0.12.0-py2.py3-none-any.whl (172kB)
    100% |████████████████████████████████| 174kB 3.9MB/s
Collecting pluggy (from python-language-server)
  Downloading https://files.pythonhosted.org/packages/ba/65/ded3bc40bbf8d887f262f150fbe1ae6637765b5c9534bd55690ed2c0b0f7/pluggy-0.6.0-py3-none-any.whl
Collecting parso>=0.2.0 (from jedi>=0.12->python-language-server)
  Downloading https://files.pythonhosted.org/packages/cd/3e/5908f9577dbd1e5df53e64349bfd11e46b726c1e4d8cd676bbe8aa4de316/parso-0.2.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 2.4MB/s
Installing collected packages: future, parso, jedi, pluggy, python-language-server
  Running setup.py install for future ... done
  Running setup.py install for python-language-server ... done
Successfully installed future-0.16.0 jedi-0.12.0 parso-0.2.1 pluggy-0.6.0 python-language-server-0.19.0
```

**Comment by Muthu2093** [comment]
Great.... I faced a similar issue while installing mysqlclient for python
sudo pip3 install MySQL client

Issue Resolved

**Comment by shreyashk09** [comment]
In order to connect to mysql from python (mine 3.7) (import mysql.connector), I used 'pip install mysql-connector-python'. Worked for me

**Comment by Kundan-Rwanda** [comment]
Thanks @shreyashk09  for me also 'pip install mysql-connector-python' worked

**Comment by jokinen77** [comment]
I had this problem when I tried to install xgboost-lib in virtual environment on mac. I was able to install it in first time but then second time I had this problem. I did the same as _schalkneethling commented on 9 Jun_ but it didn't work. Then I renamed _/Library/Developer/CommandLineTools_ folder and installed xcode command line tools again.

> xcode-select --install

This worked for me. I don't know if it was only the reinstalling command line tools or was it because of both.

**Comment by TaoYang-z** [comment]
I have a seem question when i install minepy ,and then i try they way you did ,finally success,thank u
here is my code
`sudo pip3 install --upgrade pip setuptools wheel`
`sudo pip3 install minepy`

**Comment by ghost** [comment]
Using conda, mine was fixed by executing:
`conda install shapely`
If you are using pip try:
`pip install shapely`

**Comment by gautam-404** [comment]
I had the same issue with pip. Executing: `sudo python -m pip install scipy`  worked for me

**Comment by bjxgcl** [comment]
xcode-select --install
worked for me

**Comment by serome111** [comment]
una imagen de docker es la solución, con eso te ahorras errores internos que tiene mac con las actualizaciones de herramientas de python

**Comment by unnir** [comment]
with conda you can do this: 

`conda install py-xgboost
`

**Comment by Shragkd** [comment]
I am trying to install pyradar in ubuntu 18.04 with python 3.6 using pip

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-itd9hctk/pyradar/  is the error I am getting.

I have updated setuptools and development packages too. Please help

**Comment by Umair4345** [comment]
Hello can someone please help me with this. I have tried everything mentioned above but the error doesn't go away.

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8z/gpqdyh8x14ddw7p75n63wzkh0000gn/T/pip-install-45NKk3/psycopg2/

**Comment by Anonymous1845973** [comment]
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-44321s9y/distribute/

**Comment by tongpinmo** [comment]
when i do thid command:
pip2 install -U scikit-image 
the problem is :+1: 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wt8Rvr/matplotlib/
i don't konw why?

**Comment by LK2018** [comment]
> when i do thid command:
> pip2 install -U scikit-image
> the problem is 
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wt8Rvr/matplotlib/
> i don't konw why?

i am also this question

**Comment by ch21** [comment]
I used pip install psycopg2-binary
and it worked for me. thanks for the help guys.

**Comment by steve7158** [comment]
For me the problem was while installing psycopg2
Sollution:
For python 2:
sudo apt-get install libpq-dev python-dev
For python 3
sudo apt-get install libpq-dev python3-dev

**Comment by udothemath** [comment]
Please try "xcode-select --install" as mentioned by @bjxgcl

It also works for me.

**Comment by maaaslani11** [comment]
Help please I am a new user of python, and I try to install "scikit-spectra" with this; "sudo python3 -m pip install scikit-spectra" I got the error as " ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cv_doa98/scikit-spectra/setup.py", line 16, in <module>
        with open('requirements.txt', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cv_doa98/scikit-spectra/"

Any suggestions? Thanks...

**Comment by yuliansen** [comment]
Help i was trying to clone pip install git+https://github.com/zhangchiyu10/pyC45.git , and ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\YULIAN~1\AppData\Local\Temp\pip-req-build-_iw_ga7h\
i have updated my setup to the latest, and nothing changes. help what should i do

**Comment by prem2017** [comment]
> I have a seem question when i install minepy ,and then i try they way you did ,finally success,thank u
> here is my code
> `sudo pip3 install --upgrade pip setuptools wheel`
> `sudo pip3 install minepy`

This did it for me.

**Comment by shinabarger** [comment]
> I have a seem question when i install minepy ,and then i try they way you did ,finally success,thank u
> here is my code
> `sudo pip3 install --upgrade pip setuptools wheel`
> `sudo pip3 install minepy`

Tried so many things and this finally worked. thank you!!

**Comment by YashithChanuka** [comment]
sudo pip3 install mysql-connector-python
This command worked for me.

**Comment by acctn** [comment]
pip3 install python-openstackclient

**Comment by m0caa** [comment]
> Please update setup tools `pip install -U setuptools`

I tried that and many other so many times. Won't work.

**Comment by hamidnawaz28** [comment]
pip install --upgrade pip setuptools wheel
worked for my case

**Comment by azmats** [comment]
> I have a seem question when i install minepy ,and then i try they way you did ,finally success,thank u
> here is my code
> `sudo pip3 install --upgrade pip setuptools wheel`
> `sudo pip3 install minepy`

**Comment by husnullin5001** [comment]
on Fedora:
dnf install python3-devel
sudo dnf -y groupinstall "Development Tools"

// and maybe these optional packages:
pip3 install --upgrade pip setuptools wheel
pip3 install pipenv

**Comment by MohsineF** [comment]
If this error still pops up just try to re-install pip from this file [https://bootstrap.pypa.io/get-pip.py](url).
`python3 get-pip.py`
Then ensure pip, setups-tools and wheel are up to date:
`python3 -m pip install --upgrade pip setuptools wheel`
Hope this helps !

**Comment by darshDM** [comment]
> For me the problem was while installing psycopg2
> Sollution:
> For python 2:
> sudo apt-get install libpq-dev python-dev
> For python 3
> sudo apt-get install libpq-dev python3-dev

hey thanks it helped

**Comment by MdJeweleIslam** [comment]
`python -m pip install --upgrade pip setuptools wheel`
Requirement already up-to-date: pip in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (20.0.1)
Requirement already up-to-date: setuptools in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (45.1.0)
Requirement already up-to-date: wheel in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (0.33.6)


### pip, setuptools and wheel all are updated but I am still facing issue for  Scripy Installation.

ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-r_fcatzh\\Scripy\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-r_fcatzh\\Scripy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-install-r_fcatzh\Scripy\pip-egg-info'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-r_fcatzh\Scripy\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-r_fcatzh\Scripy\setup.py", line 96, in <module>
        description=get_description(packages[0], PACKAGE_DIR),
      File "C:\Users\User\AppData\Local\Temp\pip-install-r_fcatzh\Scripy\setup.py", line 47, in get_description
        pkg = __import__(package, level=1)
    KeyError: "'__name__' not in globals"
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by cheh-med** [comment]
hello you should just install it other way using cmd terminal it works without error, then go find your lib 
in C:\Users\.........\AppData\Local\Programs\Python\Python38-32\Lib\site-packages
there you will find items you downloaded ...... then copy it to your project libarary
C:\Users\........\PycharmProjects\projectname\venv\Lib\site-packages

you may use liclipse instead pycharm community version it works without problem

welcome everybody

**Comment by Arhamtahir** [comment]
Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by SergeShkurko** [comment]
For me fixes after: `sudo apt-get install libpq-dev`

[original](https://ru.stackoverflow.com/a/687978/298451)

**Comment by bramses** [comment]
I used pip3 instead of pip and it worked for me!

I was attempting to install Sphinx:

```
 File "<string>", line 17, in <module>

  File "/private/var/folders/l0/1n78l_551rv_f1g_klmmj7jh0000gn/T/pip_build_macbookpro/sphinx/setup.py", line 8, in <module>

    import sphinx

  File "sphinx/__init__.py", line 20, in <module>

    from .deprecation import RemovedInNextVersionWarning

  File "sphinx/deprecation.py", line 29

    def deprecated_alias(modname: str, objects: Dict, warning: Type[Warning]) -> None:

                                ^

SyntaxError: invalid syntax
```

**Comment by mengshiwu** [comment]
> I have a seem question when i install minepy ,and then i try they way you did ,finally success,thank u
> here is my code
> `sudo pip3 install --upgrade pip setuptools wheel`
> `sudo pip3 install minepy`

thank you so much! i have solved my question  by sudo pip

**Comment by surajmahendra2552** [comment]
i am new to programming language of python i am using visual studio code as mentioned in the title and my os is windows 8.1 pro and my python version is 3.7.2

the following is the error:
C:\Users\SURAJ MAHENDRA\Desktop>pip install pyttsx3
Collecting pyttsx3
Using cached pyttsx3-2.84-py3-none-any.whl (39 kB)
Collecting pyobjc>=2.4
Using cached pyobjc-6.1-py3-none-any.whl (2.9 kB)
Collecting comtypes; "win32" in sys_platform
Using cached comtypes-1.1.7.zip (180 kB)
Collecting pyobjc-framework-SecurityInterface==6.1
Downloading pyobjc-framework-SecurityInterface-6.1.tar.gz (23 kB)
ERROR: Command errored out with exit status 1:
command: 'e:\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\SURAJM1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\setup.py'"'"'; file='"'"'C:\Users\SURAJM1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\SURAJM1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\pip-egg-info'
cwd: C:\Users\SURAJM1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface
Complete output (15 lines):
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\SURAJM1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\setup.py", line
23, in
extra_link_args=["-framework", "SecurityInterface"],
File "C:\Users\SURAJM1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\pyobjc_setup.py", line 408, in Extension
os_level = get_os_level()
File "C:\Users\SURAJM~1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\pyobjc_setup.py", line 218, in get_os_level
pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
File "e:\python\lib\plistlib.py", line 99, in readPlist
with _maybe_open(pathOrFile, 'rb') as fp:
File "e:\python\lib\contextlib.py", line 112, in enter
return next(self.gen)
File "e:\python\lib\plistlib.py", line 82, in _maybe_open
with open(pathOrFile, mode) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

i have tried many times by changing the directory and even turned to pycharm but to no avail.
i just cant understand whats the problem. can anyone help me and please explain me layman's language as i am new.
thanking you sir/madam.

**Comment by anisatulafifah** [comment]
**I have the same problem and i have been try many times by change directory but it's not work for my case. Anyone can help me?**


C:\Users\Hp\Documents\GitHub\twint>pip3 install twint
Collecting twint
  Using cached twint-2.1.16.tar.gz (30 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hp\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hp\\AppData\\Local\\Temp\\pip-install-c8lvadyl\\twint\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hp\\AppData\\Local\\Temp\\pip-install-c8lvadyl\\twint\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Hp\AppData\Local\Temp\pip-install-c8lvadyl\twint\pip-egg-info'
         cwd: C:\Users\Hp\AppData\Local\Temp\pip-install-c8lvadyl\twint\
    Complete output (26 lines):
    Traceback (most recent call last):
      File "c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2864, in get_entry_map
        ep_map = self._ep_map
      File "c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2822, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hp\AppData\Local\Temp\pip-install-c8lvadyl\twint\setup.py", line 64, in <module>
        'Programming Language :: Python :: Implementation :: CPython',
      File "c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 132, in _install_setup_requires
        (k, v) for k, v in attrs.items()
      File "c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 423, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 657, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2867, in get_entry_map
        self._get_metadata('entry_points.txt'), self
      File "c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2538, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ccordoba12** [comment]
To all people that are directed here by a google search or something: unless you're running `pip3 install python-language-server`, your problem has **nothing** to do with this package.

Therefore, please don't report it here. Thanks!
