### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by gvanrossum** [palantir/python-language-server#388]
Excuse me if I'm dumb, but I'm new to both vscode and pyls, and I don't know anything about node.js either. How does one typically configure vscode to use pyls? By default it comes with a different Python package. I looked at README.rst and found instructions for developing pyls against vscode (which is my ultimate plan :-) but those instructions seem broken too:
```
$ yarn install .
yarn install v1.7.0
error `install` has been replaced with `add` to add new dependencies. Run "yarn add ." instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
$ yarn add .
yarn add v1.7.0
(node:23850) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/5] 🔍  Validating package.json...
warning vscode-client@0.0.1: The engine "vscode" appears to be invalid.
[2/5] 🔍  Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
What am I missing? (My ultimate goal is to write a plugin that adds access to mypy's internals to allow definition lookup and other functionality for Python -- the mypy-daemon has already collected the data, it's just a matter of getting it out. See https://mypy.readthedocs.io/en/latest/mypy_daemon.html for the current state of this project.)

**Comment by gvanrossum** [comment]
Follow-up: I got the yarn thing to work with `yarn add file:.` but I'm still no closer to running pyls against the default vscode binary (i.e. not following the development recipe).

**Comment by mnazbro** [comment]
Hi, I believe the instructions were slightly misleading. The command `yarn install` (not `yarn install .`) will resolve dependencies and download them for you. You'll want to run that instead of `yarn install .`. `yarn add .` instead will add a new dependency called `.`.

**Comment by gvanrossum** [comment]
OK, thanks -- `yarn install` without `.` works. So before you close this as "fixed", I still have that other question: given a non-dev version of VS Code (and with pyls installed) how does one use pyls from VS Code? My default VS Code instance still uses the default Python extension.

**Comment by gatesn** [comment]
From within VSCode you can install the shell commands that enable you to run it from the command line: https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

After this, the `yarn run vscode` command will open VSCode in extension development mode. Within this mode, pyls will run when you open a Python file. There will also be an output panel with the pyls logs. Pressing Ctrl/Cmd+R will refresh the window and restart pyls.

At the bottom of `vscode-client/src/extension.ts` you will find where pyls is configured to run. You can change this file to add -vvv flags, or to use an absolute path to pyls.

Some more general docs are available here: https://code.visualstudio.com/docs/extensions/developing-extensions

**Comment by gvanrossum** [comment]
OK, so that's for extension developers. What do regular VS Code users do? Is there a place they can select pyls from the extensions marketplace? I don't see it here: https://marketplace.visualstudio.com/search?term=python&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by gatesn** [comment]
Oh I see. No, we have an open ticket to publish a VSCode extension to the market place: https://github.com/palantir/python-language-server/issues/194

It's not quite clear to me what the proper way to do this is. I presume we don't package a Python runtime. Can probably follow Microsoft's example: https://github.com/Microsoft/vscode-python

**Comment by DrPyser** [comment]
@gatesn Sorry if it's not appropriate to comment on a closed issue, but I'm still confused as to how to use pyls with vscode(though that may be vscode's fault). Do I have to install a plugin specifically developed for pyls which does not currently exist? My understanding of LSP was that the goal was to avoid this? 

Is there not a way to tell vscode to use pyls as the python language server?

**Comment by dalisoft** [comment]
Would be nice to use as Extension on VS(Code/Codium)
