### ISSUE TITLE
TCP mode does not work

### ISSUE THREAD

**Issue by MathieuDuponchelle** [palantir/python-language-server#39]
Simplest client possible:

```
import requests
import json


def main():
    url = "http://localhost:4000/"
    headers = {'content-type': 'application/json'}

    payload = {
        "method": "initialize",
        "jsonrpc": "2.0",
        "id": 0,
    }
    response = requests.post(
        url, data=json.dumps(payload), headers=headers).json()

if __name__ == "__main__":
    main()
```

Run pyls with:

```
pyls --tcp --host 0.0.0.0 --port 4000
```

Result:

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52078)
Traceback (most recent call last):
  File "/usr/lib64/python3.4/socketserver.py", line 617, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/meh/devel/sandbox/python-language-server/pyls/python_ls.py", line 33, in __init__
    super(PythonLanguageServer, self).__init__(*args, **kwargs)
TypeError: __init__() takes 3 positional arguments but 4 were given
----------------------------------------
```

**Comment by MathieuDuponchelle** [comment]
After looking at the source code, it is pretty obvious why this cannot work, as the handler class passed to socketserver.ThreadingTCPServer , though it inherits from socketserver.StreamRequestHandler, overrides its __init__ method to take (rfile, wfile), which has nothing to do with the arguments that will be passed to it when being constructed.

I'm really confused by how this is set up, has this ever worked ??

**Comment by gatesn** [comment]
Unclear if it has... I'm also not sure if there is much need for supporting it. Ideally, the workspace exists on the same machine as the language server so in most cases JSONRPC over stdio is sufficient. 

Either we remove it completely, or we stop trying to use the same handler class for a socket server and a stdio server. Happy to take a look here at some point.

**Comment by MathieuDuponchelle** [comment]
Think I'll just fix that, I'd much rather not communicate through stdio tbh :) Do you have any idea whether other language server implementations work through stdio only ?

**Comment by gatesn** [comment]
I don't know of any that work exclusively through stdio but all that I have seen support both stdio and tcp:

https://github.com/sourcegraph/go-langserver/blob/master/main.go#L17
https://github.com/felixfbecker/php-language-server/blob/master/bin/php-language-server.php#L96

etc.

Certainly need to get TCP fixed though I agree.

**Comment by MathieuDuponchelle** [comment]
Hehe nice, ended up doing other stuff, thanks !

**Comment by MathieuDuponchelle** [comment]
It does break on python 3 though I'm afraid (unicode error)

```
^C meh  ⓔ  pls_venv   master  ~  devel  sandbox  python-language-server  pyls --tcp --host 0.0.0.0 --port 4000
2017-04-26 04:59:39,927 UTC - ERROR - pyls.server - Language server shutting down for uncaught exception
Traceback (most recent call last):
  File "/home/meh/devel/sandbox/python-language-server/pyls/server.py", line 26, in handle
    data = self._read_message()
  File "/home/meh/devel/sandbox/python-language-server/pyls/server.py", line 69, in _read_message
    content_length = self._content_length(line)
  File "/home/meh/devel/sandbox/python-language-server/pyls/server.py", line 55, in _content_length
    if line.startswith("Content-Length: "):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
^C meh  ⓔ  pls_venv   master  ~  devel  sandbox  python-language-server  deactivate
```

**Comment by MathieuDuponchelle** [comment]
And with the sample script the call to requests.post blocks in python 2 :(
