### ISSUE TITLE
Completions not working for modules installed within a pipenv virtual environment?

### ISSUE THREAD

**Issue by mjlbach** [palantir/python-language-server#390]
I use pipenv to manage my python virtual environments/projects. I've noticed that when I create and install pyls within a pipenv virtual environment, only standard modules (os, sys, etc.) have completions. External modules like numpy, requests, etc. do not show completions. The only combination that currently gives me external module completion is when I've installed pyls within an activated virtualenv created via the built-in venv module which also contains the external modules.

**Comment by rebelot** [comment]
Any news on this? I experience the same issue. I have created a virtualenv which has access to systems modules and Jedi is properly listing modules that are non directly installed in the venv, nonetheless pyls only lists standard modules. It is like pyls is explicitly passing a syspath to Jedi which is inconsistent with Jedi’s ways of detecting it

**Comment by rebelot** [comment]
FYI I use neovim, and specifying `pyls` as `python -m pyls` solved the issue for me

**Comment by mjlbach** [comment]
@tommasolaurenzi This solution did not work for me with pipenv. Thanks for the suggestion though. I believe the issue may be upstream with how Jedi reads sys.path

**Comment by justinmoon** [comment]
I'm having same problem.

Neither autocomplete nor go-to-definition work for me using vim with the ALE plugin when using a pipenv environment. Problem could be with ALE but figured I should chime in here.

Linting works fine. Autocomplete and go-to-definition work for standard library. 

edit:

Seems Jedi is also [used for go-to-definition](https://github.com/palantir/python-language-server/blob/develop/pyls/plugins/definition.py). So @mjlbach's theory makes some sense in my case.

**Comment by tacho** [comment]
I was having the same problem, but only under macOS, Linux was fine, so this got me digging. Fixed in https://github.com/davidhalter/jedi/pull/1212.

**Comment by esn89** [comment]
@rebelot 

How did you manage to set this?  Is this in LanguageClient-neovim?

**Comment by nicksspirit** [comment]
What I did to get pyls to get me proper code completions was to install pyls in my virtual environment and then use an executable script to start the pyls server with the virtual environment activated.
I am using sublime text as my editor and then fish as my terminal shell. I then wrote this fish script (easily can be rewritten in bash)

```fish
#!/usr/bin/env fish

echo "["(date)"] "(pwd) >> ~/Developer/pyls.log

set CWD (pwd)

if test -n "$VIRTUAL_ENV"
    source "$VIRTUAL_ENV"/bin/activate.fish
    "$VIRTUAL_ENV"/bin/pyls

else if test -d "$CWD/.venv"
    source "$CWD"/.venv/bin/activate.fish
    "$CWD"/.venv/bin/pyls

else
    exit
end
```

Then in sublime text I set the command to start the pyls server to be the script in sublime text's LSP settings.

```json
"pyls":
		{
			"enabled": true,
			"command":["/path/to/script/pyls.fish"],
			"syntaxes":
			[
				"Packages/Python/Python.sublime-syntax",
				"Packages/MagicPython/grammars/MagicPython.tmLanguage"
			]
		},
```

**Comment by 15cm** [comment]
#657 supports passing your own syspath. I use Emacs and manage to pass my `pyenv` syspath to `pyls` in https://github.com/emacs-lsp/lsp-mode/pull/1393
