### ISSUE TITLE
slow completions when running from different environment

### ISSUE THREAD

**Issue by dragomirecky** [palantir/python-language-server#397]
Hi,
First of all thanks for this fantastic project! I am very much looking forward to using it, I just have a small issue integrating it into my working environment.

**Environment**:
- neovim (v0.3.1)
- LanguageClient-neovim (8603ed)
- python-language-server (v0.19.0), jedi (0.12.1)

I use `pyenv` to manage my virtual environments. I have one `neovim3` virtualenv (python 3.6.4) that neovim uses. All my projects use a different environment. My goal was to have `pyls` installed in this `neovim3` virtualenv only and have it work for my other environments.

**Problem**:
If used as described, autocompletion is super slow. The first one takes a very long time and following ones for about 3 seconds. If I install `pyls` into the project's environment I work on and run it from there, there is no problem, and everything works great.

Any idea, what might be wrong?

**Comment by hrehfeld** [comment]
Any progress on this?

**Comment by vv111y** [comment]
I'm having the same issue https://github.com/tigersoldier/company-lsp/issues/54, but I am not in a virtualenv.

*Environment*
- Spacemacs (develop, updated), updated packages
- jedi(0.12.1)
- python-language-server(0.19.0)

**Comment by dragomirecky** [comment]
Hi, 
I just had a look and found out there were several updates to python-language-server from the time I have opened this issue. I tried to update and voilà, it helped! 🎉

I am closing this issue as my problem is solved (and I believe it's going to be the same for @vv111y). 

Big thanks @gatesn for your work!
