### ISSUE TITLE
unclear how to supply configuration options

### ISSUE THREAD

**Issue by tmc** [palantir/python-language-server#398]
I'm using this via https://github.com/natebosch/vim-lsc ala:

let g:lsc_server_commands = {'python': 'pyls'}

how do I supply additional configuration?

**Comment by ghost** [comment]
I really like your LS implementation.  Light, simple... works.  (also not sure what lint plug I will use.. any suggestion welcome).
'plys' ref the language server, which can be extended: https://github.com/palantir/python-language-server
ex: pip install 'python-language-server[all]'.  Not sure what additinal config you mean...?  I suspect the language server can be use by a linter, systax checker/code completion, etc.

**Comment by rebelot** [comment]
he wants to set up a config file to set the language server options like it is possible in VSCode. That question though is to be asked to the provider of the Language Client in use.

**Comment by tmc** [comment]
@tommasolaurenzi can you elaborate? Are you saying this concern is within the responsibility of the client-server comms?

That this plugin emphasizes vscode configuration made me think it was in-scope to raise this here.

**Comment by rebelot** [comment]
@tmc it is indeed concern of the client (the plugin calling the lang server) to pass a config file to the server. Every language server is designed to work with VSCode, as the language server protocol itself is a microsoft thing. Language Clients just emulate VSCode ability to communicate with language servers and they usually support a config file with the same VSCode syntax (be aware that options written in a json format have to be split, they are not dot-expanded, so:
```
{
   " pyls.plugins.whatever" = true
}
```
becomes
```
{
    "pyls": {
        "plugins": {
            "whatever": true
         }
    }
}
```
the path of such file though has to be discovered within you vim plugin. With LanguageClient-neovim specify that path explicitly is just one `let g:LanguageClient_settingsPath = ...` away. Idk about vim-lsc

**Comment by tmc** [comment]
Thanks.
