### ISSUE TITLE
Completion on numpy root slow.

### ISSUE THREAD

**Issue by hifall** [palantir/python-language-server#399]
I am on Ubuntu 16.04/Python 3.7.

When I type `numpy.`, it takes like 10+ seconds for the completion list to show up, on a typical VPS. Although completion lists for built-in modules like `sys` are much faster.

Is there any optimization we can apply here?

Thanks!

**Comment by gatesn** [comment]
This is a question for Jedi, the library we use for our completions. You do have the option to import numpy greedily but that just means you pay the cost at startup time instead of first completion.
