### ISSUE TITLE
Document highlighting doesn't work on Windows

### ISSUE THREAD

**Issue by AmjadHD** [palantir/python-language-server#402]
This is the result of debugging LSP client for sublime text:
```
LSP:  --> textDocument/documentHighlight
LSP:      None
```
using pyls 0.19.0.

**Comment by gatesn** [comment]
The protocol allows for documentHighlight to return null: https://microsoft.github.io/language-server-protocol/specification#textDocument_documentHighlight

It seems we return null in the case of highlight returning an empty list: https://github.com/palantir/python-language-server/blob/develop/pyls/python_ls.py#L207

**Comment by AmjadHD** [comment]
@gatesn, actually the problem is windows specific:
The test `uris.uri_with(document.uri, path=definition.module_path) == document.uri` in https://github.com/palantir/python-language-server/blob/48eedeaeff5f570d14e7845c12494e46649d3193/pyls/plugins/highlight.py#L16
always returns `False`.
I added some debugging, and it turns out the uris differ in the drive's letter's case:
```
server: 2019-12-09 21:31:17,826 UTC - ERROR - pyls.plugins.highlight - definition.module_path == c:\Users\User\AppData\Local\Programs\Python\Python38\Lib\site-packages\pyls\plugins\highlight.py
server: 2019-12-09 21:31:17,826 UTC - ERROR - pyls.plugins.highlight - uris.uri_with(document.uri, path=definition.module_path) == file:///c:/Users/User/AppData/Local/Programs/Python/Python38/Lib/site-packages/pyls/plugins/highlight.py
server: 2019-12-09 21:31:17,827 UTC - ERROR - pyls.plugins.highlight - document.uri == file:///C:/Users/User/AppData/Local/Programs/Python/Python38/Lib/site-packages/pyls/plugins/highlight.py
```

**Comment by AmjadHD** [comment]
Anyone seeing this ? @ccordoba12 ?

**Comment by AmjadHD** [comment]
Hellloo, @gatesn, @ccordoba12.

**Comment by gatesn** [comment]
Apologies, this got lost in my email. I'll look to add a test for the case you mentioned and fix it up

**Comment by gatesn** [comment]
@AmjadHD could you test the ngates/compare-paths branch?

**Comment by AmjadHD** [comment]
I'm not sure how to do that:
```
C:\Users\User>pip install -e git+https://github.com/palantir/python-language-server.git
ERROR: Could not detect requirement name for 'git+https://github.com/palantir/python-language-server.git', please specify one with #egg=your_package_name
```

**Comment by goanpeca** [comment]
maybe

`pip install git+https://github.com/palantir/python-language-server.git@ngates/compare-paths` ?

**Comment by AmjadHD** [comment]
thanks i already figured it out, @gatesn now it's working.
