### ISSUE TITLE
CLI client?

### ISSUE THREAD

**Issue by gennad** [palantir/python-language-server#408]
Hi, first of all, sorry for a noob question.

I'd like to experiment with the language server to see how it works with my codebase. 
Is it possible to run language server's methods with a CLI client? Are there any? (could not find) If not, is there any workaround besides using editor?

Thank you

**Comment by gatesn** [comment]
I can recommend that you find a language client to test things out with. If you can configure the command used by the language client you can wrap up pyls to store it's input and output:

`bash -c 'tee /tmp/pyls-input | pyls | tee /tmp/pyls-output`
