### ISSUE TITLE
Syntax error diagnostics.

### ISSUE THREAD

**Issue by hifall** [palantir/python-language-server#409]
My env: Ubuntu 16.04 LTS.

I notice when the linters are enabled, there are some style-level diagnostics info like `there-should-be-some-space-here`. However, I can't make syntax-level diagnostics to work. For example:

<img width="550" alt="screen shot 2018-08-29 at 12 29 53 am" src="https://user-images.githubusercontent.com/5734293/44736942-38cd8c00-ab23-11e8-96f5-1da3494c2494.png">

In the above example, clearly the snippet would not compile because of the syntax error. But the desired diagnostics doesn't show.

Is syntax-level diagnostics supposed to work?

**Comment by gatesn** [comment]
Yes it should, it should be provided as part of the pyflakes plugin

**Comment by hifall** [comment]
No, not working for me.

Pyflakes has been installed like this:

`pip install 'python-language-server[Pyflakes]'`

I'd like to know how to get this fixed.
