### ISSUE TITLE
[neovim/pyls] pyls ignores my ~/.config/flake8 settings to ignore docstring warnings

### ISSUE THREAD

**Issue by esn89** [palantir/python-language-server#417]
Hi, 

I have a ~/.config/flake8 set up like so:
`[flake8]`
`ignore = D100,D101,D102,D103,D104,D105,D107`

Because I am using neovim with LanguageClient-neovim, I have a ~/.vim/settings.json config like so:
```
{
    "pyls": {
	"configurationSources": ["flake8"],
        "plugins": {
            "pyflakes": {
                "enabled": true
            },
            "pydocstyle": {
                "enabled": false
            }
        }
    }
}
```
And this is to squelch the warnings that look like this:
https://i.imgur.com/tSHWsAl.png

With all these settings, I am still getting this warning in my code, could someone help me out please?

Thanks!

**Comment by gatesn** [comment]
@esn89 are you able to upload the pyls logs?

**Comment by esn89** [comment]
@gatesn 

Where can I find the pyls logs?  I will be more than happy to get them to you

**Comment by gatesn** [comment]
Your language client might do something with them as by default they’re written to stderr 

However, you can also pass a “—log-file” argument to have them written to disk

**Comment by esn89** [comment]
Is this the log you're looking for?  https://pastebin.com/28dtzHpY

**Comment by esn89** [comment]
Sorry, turns out this was an issue with a .pylintrc.
