### ISSUE TITLE
Server crashes immediately with Neovim Language Client on Windows

### ISSUE THREAD

**Issue by svermeulen** [palantir/python-language-server#434]
Running `pip install python-language-server` and `pip install python-language-server[all]`

Then setting up dein in neovim like this:

```
call dein#add('Shougo/deoplete.nvim')

call dein#add('autozimu/LanguageClient-neovim')
```

And configuring language client like this:

```
let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls', '-v'],
    \ }
```

Causes an immediate crash every time I open a python file.   I tried learning more about what is going on but couldn't get anywhere, not even a simple error message.

**Comment by tomv564** [comment]
Looks like the same issue reported on Sublime Text here: https://github.com/tomv564/LSP/issues/426

Reverting to 0.20 fixes the issue.
I wonder if the processid sent to the language server is correct?

**Comment by svermeulen** [comment]
I can confirm that downgrading fixes the crash

**Comment by gatesn** [comment]
I wonder if we should make the pid checking optional? Seems like it causes issues in docker and elsewhere

**Comment by gatesn** [comment]
@JiahuiJiang

**Comment by jiahuijiang** [comment]
@gatesn they can just not pass in the pid if they don't want to have the check? Do you know what's the reasons that there are issues in docker?

**Comment by yssource** [comment]
The crash happens to me also.

`lsp-python has exited (exited abnormally with code 1)`

**Comment by deathaxe** [comment]
The issue is caused by the following line:

https://github.com/palantir/python-language-server/blob/1dc1fba965499f95dba1f20d6356c8e12fb0f4c2/pyls/_utils.py#L128

It does actually kill the parent process rather than checking, whether it exists on Windows.

see python documentation: https://docs.python.org/3/library/os.html?highlight=os%20kill#os.kill



I wonder if the alive check can be handled via the pipe connection to the client as well. LSP as an example detects a broken pipe, which is most likely caused by a crashed pyls process. Maybe this would work the other way round as well?

**Comment by lambdacn** [comment]
@deathaxe same problem on Mac [#458](https://github.com/emacs-lsp/lsp-mode/issues/458#issuecomment-433851100)

**Comment by deathaxe** [comment]
If `os.kill(pid,0)` doesn't work on Mac as well, I vote to completely revert the related commits and wait for a better solution to check for parent process to be alive.

While trying to fix it for Windows I even got the feeling that it is useless anyway as each time I killed the owning process, the pyls process died as well even on 0.20 which does not include the parent process check.

**Comment by jiahuijiang** [comment]
Tested on mac and os.kill(pid, 0) doesn't actually kill the process for me :/ But happy to revert the commit completely and find a better solution

**Comment by deathaxe** [comment]
Not sure about the tcp/ip interface, but if stdio is used, the pyls process should be able to detect a broken pipe. This is a quite reliable indicator for the owning process to have died. The LSP package for Sublime Text uses that to detect, whether pyls died.
