### ISSUE TITLE
Ways to disable pyls linting

### ISSUE THREAD

**Issue by wanchaol** [palantir/python-language-server#449]
do you have a way to disable the whole linting for pyls? I don't need the linting at all but I do want to use other features.

**Comment by eugene-bright** [comment]
[Configuration][1] section of README gives some hints.
If you are `VS Code` user then most of the settings [are there already][2]. Look for `pyls.plugins.*.enabled` pattern.
This options can be passed to the language server as a part of [Initialization Request][3] with optional `initializationOptions` parameter.
Sometimes such options can be sent with [DidChangeConfiguration Notification][4] later in time if language server supports it.
As I see pyls [supports both of this ways][5].
But the means of making your IDE to pass the options to server depends on it.
In addition I should mention that flakes8 and pycodestyle fine-grained configuration can be set by files.

Which IDE do you use?

[1]: https://github.com/palantir/python-language-server#configuration
[2]: https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json
[3]: https://microsoft.github.io/language-server-protocol/specification#initialize
[4]: https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration
[5]: https://github.com/palantir/python-language-server/blob/4fc34c6d3a92de67f2b814e84921bf426939e590/pyls/config/config.py#L85

**Comment by eugene-bright** [comment]
Also you can uninstall some pyls plugins to make it less verbose.
```
pip3 uninstall pyls-mypy
```

I can't find one specific toggle to disable all linting at once.

**Comment by wanchaol** [comment]
@eugene-bright thanks a lot for the detailed reply! I just use Vim to configure pyls, so it's pretty hard to configure if there's no `initalizationOptions` for disabling all, but I will try your suggestions :)

**Comment by eugene-bright** [comment]
Some additional tips for LanguageClient-neovim.
https://github.com/autozimu/LanguageClient-neovim/issues/448#issuecomment-392491861

**Comment by AmjadHD** [comment]
is it possible to disable pyflakes ?

**Comment by eugene-bright** [comment]
Please look at the link above.

The LSP client configuration method depends on the client.
