### ISSUE TITLE
Unable to complete Flask object

### ISSUE THREAD

**Issue by Trapez** [palantir/python-language-server#456]
```
from flask import Flask

app = Flask(__file__)
app.                          # This fails, see log
app.r                         # This succeeds
```

[pyls.log](https://github.com/palantir/python-language-server/files/2613232/pyls.log)

**Comment by kashewnuts** [comment]
@Trapez Please try https://github.com/palantir/python-language-server/releases/tag/0.22.0.
I could do it with this version.

**Comment by Trapez** [comment]
Yes, that version works fine. Great news!
