### ISSUE TITLE
pyls spawning hundreds of Python processes

### ISSUE THREAD

**Issue by gmstriga** [palantir/python-language-server#458]
After maybe half an hour of using TabNine's semantic autocomplete with Python, my process tree looks like this:

![image](https://user-images.githubusercontent.com/38641699/49693104-17276c00-fb38-11e8-85a6-c3beaef33c6f.png)

Right now there's about 300 processes total in there, but my highscore is 1000+ before I noticed. Almost all of them are children of pyls. It looks like the processes aren't finishing properly and just hanging around.

**Comment by gatesn** [comment]
Can you try reproducing with jedi 0.12.1? I saw similar behaviour with 0.13.0 on Linux but haven’t had time to dig into it yet

**Comment by gmstriga** [comment]
It doesn't seem to happen with jedi 0.12.1. After an hour, pyls is still sitting there with one Python process.

**Comment by sdemura** [comment]
Running into same issue on a linux machine. jedi 0.13.1 + python-language-server:master and my machine locks up within minutes from running out of memory.

**Comment by kadrach** [comment]
See davidhalter/jedi#1242.

**Comment by gatesn** [comment]
This is resolved in Jedi now
