### ISSUE TITLE
textDocument/signature help calls parameters params

### ISSUE THREAD

**Issue by danr** [palantir/python-language-server#46]
According to `protocol.md` it is named `parameters` , but `pyls` returns `params`. Example with `subprocess.call`:

```
{
  "jsonrpc": "2.0",
  "result": {
    "signatures": [
      {
        "activeParameter": 0,
        "documentation": "Run command with arguments.  Wait for command to complete, then\nreturn the returncode attribute.\n\nThe arguments are the same as for the Popen constructor.  Example:\n\nretcode = call([\"ls\", \"-l\"])",
        "params": [
          {
            "documentation": "",
            "label": "popenargs"
          },
          {
            "documentation": "",
            "label": "kwargs"
          }
        ],
        "label": "call(*popenargs, **kwargs)"
      }
    ],
    "activeSignature": 0
  },
  "id": 9
}
```

HTH and thanks for your work on `pyls`!

**Comment by danr** [comment]
Oh, and `activeParameter` should under `result`, not `signatures[0]`. (Indeed not as general as you have made it to be)

**Comment by tomv564** [comment]
The fix has been sitting waiting for a CLA to be signed for more than 2 weeks (https://github.com/palantir/python-language-server/pull/41).
Perhaps the maintainer can claim ownership of the fix and credit @svenefftinge in the comments?

**Comment by gatesn** [comment]
Happy to do this, and for any other PRs
