### ISSUE TITLE
Error when running pip install: python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by NaeemUllah-BSEF15A527** [palantir/python-language-server#462]
![capture](https://user-images.githubusercontent.com/45669434/50039783-db374f80-ffec-11e8-809c-cd988b574db9.PNG)

**Comment by NaeemUllah-BSEF15A527** [comment]
Thanks in advance

**Comment by ccordoba12** [comment]
This is a problem with your installation, not something we can fix here, sorry.
