### ISSUE TITLE
Getting started contributing

### ISSUE THREAD

**Issue by nicksspirit** [palantir/python-language-server#467]
Hey guys, I am new but I have been using the python-language-server for sublime for a while and I simply love it. I really want to try and contribute but the project is kind of intimidating. Any suggestions on how I could get started.

**Comment by wangluochao902** [comment]
Did you contribute anywhere? I am a little bit lost and want to get started.

**Comment by nicksspirit** [comment]
No actually I didn't, I don't even think I would have time anymore. Closing the issue now
