### ISSUE TITLE
[Suggestion] Turn on `follow_imports` and `follow_builtin_imports` options by default

### ISSUE THREAD

**Issue by kashewnuts** [palantir/python-language-server#482]
By turning on this options, we can code jump even if you write it like `from xxx import yyy`.
Options included in this PR(#404), but these default values are `null`.
By default, I think that the user can smart code jump.

**Comment by gatesn** [comment]
@st4lk @lgeiger - given you've touched these configs before, do you know of any reason not to enable these by default?

I think we might want to flip the default in code if we do go ahead with this change though.

**Comment by st4lk** [comment]
Sounds good, no objections from my side. I kept it null to not change existing behavior.
But I agree, it makes sense to turn it on by default.

**Comment by lgeiger** [comment]
I can't think of any reason not to enable `follow_imports` by default. Though I haven't used `follow_builtin_imports` in the past, so I don't know if this works well for all builtins. I tend to prefer `follow_builtin_imports=False` but that's just personal preference.
