### ISSUE TITLE
Your company directly facilitates tyranny and imperialist murder

### ISSUE THREAD

**Issue by twome** [palantir/python-language-server#486]
What's it like working for a US defence and intelligence contractor? Do you ever really experience, in a visceral way, the shame you know you should? You're all fucking sociopathic bastards.

Cheers,
Tom

**Comment by uschi2000** [comment]
Tom, I am going to close this issue as this forum is intended for collaboration on product-specific topics. We are happy to discuss your concerns in person if you're interested, please get in touch.
