### ISSUE TITLE
Language server showing junk data in completion list

### ISSUE THREAD

**Issue by rbhanot4739** [palantir/python-language-server#490]
I wanted to give language server a try so tried using it with Neovim, however I am facing strange issue where the language server shows lot of junk data in the completion list. Below are details.

Neovim version: v0.3.2-208-g2841e89
OS : Ubuntu 16.04.5 LTS
Python version : 3.7

I installed the language server with pip.

Relevant config from my vimrc

```
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'do': 'bash install.sh'}

let g:LanguageClient_serverCommands = {
\ 'python': ['/home/rbhanot/tools/miniconda3/envs/py37/bin/pyls'], 
·\}
```

This is how completion looks inside a python file

![image](https://user-images.githubusercontent.com/19793591/52421658-84488500-2b1a-11e9-893e-62fe8138b2dc.png)

As you can see it shows directories like `Public`, `Pictures` as well in the completion list.

Please note this happens only with Python Language Server only. If I use python completion source for deoplete, the completion list is spot on and no junk data is listed.

I also installed language server for typescript and completion in javascript files was very much correct.

So can anyone please let me if this is an issue or am I missing some configuration ?

**Comment by rbhanot4739** [comment]
Anyone any update??

**Comment by rbhanot4739** [comment]
Anyone ???

**Comment by gatesn** [comment]
Hey, this seems odd. I will try to create a test to reproduce this and get back to you.

**Comment by rbhanot4739** [comment]
@gatesn Thank you.

**Comment by gatesn** [comment]
Ok, so I've traced this down to a change made in Jedi 0.13.0: https://github.com/davidhalter/jedi/commit/4b276bae87a3170672f7ddb3e00f5851fe24d562#diff-6383244f13f39fc94eb2a32e0c065d70R111

Previously, Jedi would stop traversing up the file tree when it hit the project path, now it goes all the way to the root `/` directory. Combine this with Python 3 not requiring `__init__.py` files and you end up with every directory in your parent tree showing up as a completion item. 

I agree this isn't desirable, but this is something to bring up on the jedi project itself. As such, I'm going to close out this ticket and recommend you file a follow-up on Jedi.

**Comment by rbhanot4739** [comment]
Ok Thank you very much, I will create issue on Jedi issues.
