### ISSUE TITLE
Python 3 issues - byte vs str 

### ISSUE THREAD

**Issue by IBestuzhev** [palantir/python-language-server#50]
Thanks a lot for the server, it's amazing job.

I tried to use it with python3.5 and noticed some issues with mixing `byte` and `str` usage. While it works in python2 (I think mainly because most code and paths are ascii encoded) it raises an exception in 3rd python.

So far I noticed 2 bugs affected by it.

#### Starting a server in `--tcp` mode.

`pyls.server.JSONRPCServer#_content_length` fails at `line.startswith` call, because line is raw bytes and header is an unicode string. I had to modify it to be `line.startswith(b"Content-Length: ")`. And the same applies to next line `_, value = line.split(b"Content-Length: ")`. 

Also sending back response (`pyls.server.JSONRPCServer#_write_message`) fails on write, but it works if encoded - `self.wfile.write(response.encode())`.

But this changes will break the stdin/stdout communication. So perhaps `pyls.language_server.LanguageServer` implementation needs some extra init parameter or attribute to flag if communications are in raw bytes or in unicode string.

**Comment by gatesn** [comment]
@IBestuzhev thank you so much for finding these bugs, and the thorough job of debugging them! I believe I've solved the stdio issue by always reading/writing binary.

I will open a new ticket for your other issue, then take a look at it.
