### ISSUE TITLE
Launch LS in stdio mode 

### ISSUE THREAD

**Issue by vparfonov** [palantir/python-language-server#51]
Hello, i want to start your Language Service in stdio mode as separate process and communicate with it through web IDE (not VScode). I don’t see any documentation about how it is done, could you please point me where I can find it?
Thanks

**Comment by mniewrzal** [comment]
If I'm right you just need to exec `pyls` and connect process in/out streams to LSP client.

**Comment by vparfonov** [comment]
ok thank i will try

**Comment by svor** [comment]
Hello! I've tried to run pyls from the command line but I've had an error message. What I've done:
1. Cloned https://github.com/palantir/python-language-server.git and run `pip install .`
2. Tried to run pyls: `python pyls `
as a result:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vsvydenko/codenvy/python-language-server/pyls/__main__.py", line 7, in <module>
    from . import language_server
ValueError: Attempted relative import in non-package
```

If I try run with -m parameter (`python -m pyls`), I have no outputs.

What I'm doing wrong?

**Comment by mniewrzal** [comment]
I can only write what I did to install it:
* cloned https://github.com/palantir/python-language-server.git
* go into python-language-server
* execute `pip install --process-dependency-links .`
* and just run `pyls` from command line, everything works ok

**Comment by svor** [comment]
I got the connection. Thank you!

**Comment by gatesn** [comment]
Seems to be working?
