### ISSUE TITLE
pyls passes snippets to clients that don't support it

### ISSUE THREAD

**Issue by 9ary** [palantir/python-language-server#515]
Since #499, pyls passes snippets to the client even if it declares that it doesn't support it (with `capabilities.completion.completionItem.snippetSupport`), and the only way to work around this is to pass it [specific options](https://github.com/autozimu/LanguageClient-neovim/issues/737#issuecomment-465089402).

pyls should honor standard capabilities declared by the client.

**Comment by Shougo** [comment]
I will fix the problem.  Please wait.

**Comment by Shougo** [comment]
Done.
