### ISSUE TITLE
Python 2 and 3 side by side.

### ISSUE THREAD

**Issue by kierun** [palantir/python-language-server#521]
I am in the unfortunate position to have to use Python 2 and 3. Is there a way to have neovim load the right versions of 'python-language-server[all]` for the right Python version?

**Comment by gatesn** [comment]
I think you'd have to configure neovim to use a different pyls executable based on the project. The language server supports both, so you should be able to create two virtualenvs (using `-p python2` and `-p python3`) and install pyls into both.
