### ISSUE TITLE
LSP configuration

### ISSUE THREAD

**Issue by kierun** [palantir/python-language-server#522]
Is there anywhere a clear guide to where the configuration is, what can go in it, and how to test it?

I tried `~/.vim/settings.json` but it appears to be ignored -- nothing I put in there seems to do anything.

**Comment by YodaEmbedding** [comment]
Are you here from the https://github.com/autozimu/LanguageClient-neovim/issues/737 issue? Same here!

I think the `settings.json` is supposed to belong to LanguageClient-neovim. Either LanguageClient-neovim isn't reading it or `pyls` is ignoring the configuration for disabling parameters/snippets/etc.

**Comment by kierun** [comment]
@SicariusNoctis  No, I was not aware of that one. Thanks.

**Comment by gatesn** [comment]
Pyls was indeed ignoring the client configuration for snippet support, that should be fixed in #529
