### ISSUE TITLE
Neovim gutter is not correctly updated.

### ISSUE THREAD

**Issue by kierun** [palantir/python-language-server#523]
I am not 100% sure this is this project's fault, but it's likely to be as it was working fine before I updated to version 0.25.0…

I wrote a small script from scratch, making sure I did plenty of mistakes and corrected them. However, at the end, this is what I see:
 
![screenshot](https://user-images.githubusercontent.com/3079575/54269493-60db8480-4575-11e9-8e90-b3b6eb5e9578.png)

Clearly it is not right and is super annoying.

Any idea what I am doing wrong or how to fix it?

**Comment by kierun** [comment]
[It could be related to LanguageClient-neovim issue 758 …](https://github.com/autozimu/LanguageClient-neovim/issues/758)

**Comment by gatesn** [comment]
Looks like it's fixed in https://github.com/autozimu/LanguageClient-neovim/pull/769

**Comment by kierun** [comment]
Thank you.
