### ISSUE TITLE
Make default renaming work with Jedi

### ISSUE THREAD

**Issue by weigangd** [palantir/python-language-server#530]
Could the rename functionality be defaulted (if rope is not installed) to jedi's renaming function since it is a base dependency? The readme doesn't list it for jedi.

**Comment by gatesn** [comment]
Jedi refactoring seems to be pretty experimental. Happy to look at adding it but I don't think it would be enabled by default: https://jedi.readthedocs.io/en/latest/docs/development.html#module-jedi.refactoring

**Comment by nanoant** [comment]
Guys, upcoming Jedi 0.17.0 release will support support refactoring, quote [Jedi CHANGELOG](https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst)
> Added support for Refactoring. The following refactorings have been implemented: Script.rename, Script.inline, Script.extract_variable and Script.extract_function.

Are you planning to integrate it in LSP so Rope is no longer needed?

**Comment by gatesn** [comment]
Yes, it seems Jedi is now pushing this as a more stable feature, would be very happy to remove rope as a dependency

**Comment by fsouza** [comment]
Now that Jedi 0.17.0 is out, would you consider a PR adding support for rename with Jedi? I'm eager to get rid of rope on my side 🙈  I can give it a shot if no one else is working on it already.
