### ISSUE TITLE
Not able to install rasterio libraries through pip command prompt, 

### ISSUE THREAD

**Issue by Bhupendra91** [palantir/python-language-server#548]
Any idea folks about the problem.

**Comment by Bhupendra91** [comment]
Issue as below: 
:\Python\Python37>pip install rasterio
Collecting rasterio
  Using cached https://files.pythonhosted.org/packages/ce/90/8af39cdfed9a40bd59801f101f74eab5f1562d3557806ddfa2ed86d4be0b/rasterio-1.0.22.tar.gz
    Complete output from command python setup.py egg_info:
    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
_______________________________________________________________________________________________________

Command "python setup.py egg_info" failed with error code 1 in C:\Users\BHUPEN~1\AppData\Local\Temp\pip-install-q9v4anhz\rasterio\

**Comment by Bhupendra91** [comment]
Issue as below:
:\Python\Python37>pip install rasterio
Collecting rasterio
Using cached https://files.pythonhosted.org/packages/ce/90/8af39cdfed9a40bd59801f101f74eab5f1562d3557806ddfa2ed86d4be0b/rasterio-1.0.22.tar.gz
Complete output from command python setup.py egg_info:
INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.

Command "python setup.py egg_info" failed with error code 1 in C:\Users\BHUPEN~1\AppData\Local\Temp\pip-install-q9v4anhz\rasterio\

**Comment by gatesn** [comment]
Is this related to the python-language-server?
