### ISSUE TITLE
python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cv_doa98/scikit-spectra/"

### ISSUE THREAD

**Issue by maaaslani11** [palantir/python-language-server#553]
Help please I am a new user of python, and I try to install "scikit-spectra" with this; "sudo python3 -m pip install scikit-spectra" I got the error as " ERROR: Complete output from command python setup.py egg_info:
ERROR: Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-install-cv_doa98/scikit-spectra/setup.py", line 16, in
with open('requirements.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cv_doa98/scikit-spectra/"

Any suggestions? Thanks...

**Comment by gatesn** [comment]
Is this related to the python-language-server?
