### ISSUE TITLE
Update to LSP 3.0

### ISSUE THREAD

**Issue by gatesn** [palantir/python-language-server#56]
* Use rootUri in favour of rootPath

**Comment by tomv564** [comment]
I created a PR for this as I'd like to drop support for `rootPath` in my LSP client.

The other 3.0 change is versioned changes for WorkspaceEdit, but if I understand this is optional and only if the client supports it. (see
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspaceedit)

**Comment by gatesn** [comment]
Once again thanks for this! I will review tomorrow and hopefully cut a release. Out of interest, what client are you working on?

________________________________

**Comment by tomv564** [comment]
No problem, and thanks for this server! 
I'm working on a client for Sublime Text at https://github.com/tomv564/LSP.

**Comment by gatesn** [comment]
It seems we now support LSP 3.0 given the rootUri support. Closing this ticket out since the rest of 3.0 changes are optional additions to the protocol.
