### ISSUE TITLE
Support configuration for enabling/disabling/configuring plugins

### ISSUE THREAD

**Issue by gatesn** [palantir/python-language-server#57]
As well as enabling/disabling everything, we want to:

* Pass pycodestyle / pyflakes configs
* Choose the style for Yapf (pep8, google, config file)

**Comment by wbthomason** [comment]
I already use https://github.com/w0rp/ale for linting, with a larger set of linters. Being able to disable the redundant linting `pyls` provides would be great.

**Comment by gatesn** [comment]
Would you mind telling me which client you're using? The question here is whether there is a precedent for configuring language servers already. Something I'll need to look into. It might be config files on disk, or it might initialisation opts passed in by the client, with configuration living in the clients config files.

**Comment by wbthomason** [comment]
I'm using https://github.com/autozimu/LanguageClient-neovim. Per the documentation (https://github.com/autozimu/LanguageClient-neovim/blob/master/doc/LanguageClient.txt) the only configuration options are for the client itself (though you can specify flags to be passed to a specific language server when specifying the command for said server).

The protocol spec does seem to indicate that clients can pass "initialization options" to servers (https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize-request). It's not clear if this is intended as the primary mechanism for configuring language servers (at least to me).

If using that field in the initialization request is the correct way to go, I could make a PR on the client I use to support using it (I could also make a PR to add basic configuration options to this server).

**Comment by tomv564** [comment]
The Rust language service uses **workspace/DidChangeConfiguration** as described in https://github.com/rust-lang-nursery/rls#configuration

As for storing the settings per-project:
The VS Code extension passes key-value pairs from settings.json along using that method. 
Sublime Text could store the same options in .sublime-project files.

**Comment by gatesn** [comment]
Example of configuration here: https://github.com/Microsoft/vscode-docs/blob/master/docs/extensions/example-language-server.md
