### ISSUE TITLE
Custom method support

### ISSUE THREAD

**Issue by danielnowakowski** [palantir/python-language-server#591]
I found merged changes https://github.com/palantir/python-language-server/pull/224, but it seems that they are gone at this moment.

I would like to create a plugin to python-language-server with the handling of a custom method like `textDocument/extractVariable`. Can I achieve this?

**Comment by gatesn** [comment]
Yes, this is still possible. You can create something like this:

```
from pyls import hookimpl

@hookimpl
def pyls_dispathers():
	return {'textDocument/extractVariable': whatever_handler}
```

The dispatcher classes were moved here: https://github.com/palantir/python-jsonrpc-server/blob/develop/pyls_jsonrpc/dispatchers.py
