### ISSUE TITLE
Interested in sharing maintainership with the Spyder team?

### ISSUE THREAD

**Issue by ccordoba12** [palantir/python-language-server#595]
I'm the current [Spyder](https://github.com/spyder-ide/spyder) maintainer, an IDE to do data science in Python and made with Python too. We recently switched our code completion and linting architecture to use the Language Server Protocol, and as part of that effort we found some shortcomings and bugs in the `python-language-server` we'd be happy to help you with.

We already submitted a PR (see #542) and mentioned the importance of revisiting another one (see #445) but received no response. We've also seen other recent PRs have received no feedback as well.

Given the low activity in this repo during the last months and our need for the `python-language-server` to keep alive, we would like to know if you would be interested in sharing maintainership of this project with us. We have four developers ready to help improving things, one of whom (@andfoy) has already made contributions in the past and knows very well the server and client parts of the LSP.

We really hope you agree with our proposal. Otherwise we will be forced to create a fork of this project, something we'd really like to avoid to not split the community in two.

What do you think?

**Comment by ccordoba12** [comment]
@gatesn, do you have something to say about our offer?

**Comment by gatesn** [comment]
Hi @ccordoba12, I'm just in conversation with our lawyers about what a collaboration could look like. I'll get back to you soon on this ticket.

**Comment by ccordoba12** [comment]
Thanks a lot for your answer @gatesn! Some comments that could help you to clarify the situation with your lawyers:

1. I'll be willing to sign Palantir's CLA.
2. You could add me as a "Collaborator" to this repo with write permissions. That's how I'm maintaining the [qtconsole](https://github.com/jupyter/qtconsole) repo for project Jupyter without being admin or part of their organization.
3. I'd prefer if you could also add me as a maintainer in PyPI, so I could push releases to it. This is not strictly necessary, but I've found that it's more reliable to make releases manually instead of automatically.

**Comment by ccordoba12** [comment]
@gatesn, any updates? We really like to start contributing here.

**Comment by gatesn** [comment]
So, all signed off! I will add you as a collaborator now with write permissions.

Unfortunately I can't give you access to the PyPi account since that account may now, or in the future, publish other projects.

**Comment by ccordoba12** [comment]
Thanks a lot for the great news @gatesn!

One last thing: could you add me to the group of users authorized to merge pull requests? Else I won't be able to do that, as can be seen in the screenshot below:

![Selección_014](https://user-images.githubusercontent.com/365293/59678254-33cdec00-91cc-11e9-8632-e133f1fa7ff8.png)

**Comment by gatesn** [comment]
Can you try now?

**Comment by ccordoba12** [comment]
It seems to be working, but now we need to fix issue #602 because tests are failing on Windows and Python 3.4.

Could you also remove the `branch` Appveyor requirement?

![Selección_015](https://user-images.githubusercontent.com/365293/59685282-1ef95480-91dc-11e9-9e80-ed9734af85a6.png)

That's only necessary to test PRs made with in-repo branches, which I'm not planning to do.

**Comment by ccordoba12** [comment]
@gatesn, I still can't merge PR #605 (which fixes our tests) due to the requirement on `continuous-integration/appveyor/branch` to pass.

**Comment by ccordoba12** [comment]
Sorry to bother you again @gatesn, but could you remove the requirement I mentioned above? I really can't do anything here until that's removed.

**Comment by gatesn** [comment]
Yup, just removed that as a required check.

**Comment by ccordoba12** [comment]
Thanks a lot @gatesn!

**Comment by lgeiger** [comment]
Great to see the collaboration with the Spyder team. That's great news for the Python language server ecosystem 🎉 

On other way to move forward would also to create a python-language-server GitHub organization. I'd be happy to move the [Atom python extension](https://github.com/lgeiger/ide-python/) there too, which has been suffering from not enough attention from my side lately.
