### ISSUE TITLE
Issue with pylint

### ISSUE THREAD

**Issue by mpanarin** [palantir/python-language-server#596]
Suddenly, for some reason, pylint stopped working for me.

I am on manjaro linux with all the latest update, using Emacs and lsp-mode, with all the latest updates as well. 

The main issue is - where can i search for logs of pyls or something of that sort in order to edbug the issue? I am pretty sure this is something my specific to my config, as it stopped working pretty out of nowhere without me updating anything related to matter.

**Comment by gatesn** [comment]
If you run `pyls -vvv` you should get debug logs on stderr
