### ISSUE TITLE
README: badges

### ISSUE THREAD

**Issue by rootulp** [palantir/python-language-server#6]
Potentially:
- Python versions
- MIT License
- CircleCi build status (once implemented)

**Comment by gatesn** [comment]
I've added CircleCI, how do you want to add the others?

**Comment by rootulp** [comment]
Sorry for the slow response! If we submit this package to the [Python Package Index](https://pypi.python.org/pypi), we can add a version badge similar to how the [typedjsonrpc](https://github.com/palantir/typedjsonrpc/blob/develop/README.rst) repo does it.

```
.. image:: https://img.shields.io/pypi/pyversions/typedjsonrpc.svg
     :target: https://img.shields.io/pypi/pyversions/typedjsonrpc
```

As for the license badge, I think we can add something like this:
```
.. image:: https://img.shields.io/github/license/palantir/python-language-server.svg
     :target: https://github.com/palantir/python-language-server/blob/master/LICENSE
```

**Comment by gatesn** [comment]
Thanks! So I've add the license and circle shields. Will wait for Python versions until PyPi publishing is setup in #9
