### ISSUE TITLE
Support pyls when installed with --user

### ISSUE THREAD

**Issue by karolyi** [palantir/python-language-server#600]
Hey,

I've installed this project with `pip install --user`, so I wouldn't have to install locally into all of my virtual envs I use.

However, since `~/.local/lib/python3.7/site-packages/` is not in the path when starting pyls, it fails to start.

I've worked it around with having it added to `~/.local/bin/pyls` in `sys.path`, but it would be nice to have it automatically there so I wouldn't have to update it each time there's a package update.

Any chance of getting this done? Should I try to create a PR for it?

**Comment by karolyi** [comment]
... or maybe that's not a good idea at all. pyls is in `~/.local/bin` will be hooked up with the python in the virtualenv that's installed from. If someone has virtualenvs with different python versions, that might end up with weird results.

Anyway, thoughts?

**Comment by mcepl** [comment]
That’s weird. I have pyls installed in ``--user`` as well, and it seems to work just fine (with ``vim-lsp``). Are you sure the problem is not in the client?

**Comment by karolyi** [comment]
it works when you set up a `PYTHONPATH` with your local site packages. it's how I use it now.

**Comment by mcepl** [comment]
Right, we have it apparently hard written in our system Python binaries. ``sys.path`` contains ``~/.local/lib/python*/site-packages`` automagically. So, that’s probably how it is meant to work, isn’t it?

**Comment by karolyi** [comment]
Not sure what you mean by 'system Python binaries'. When setting up a venv, afaik Python doesn't add the `~/.local...` path to `sys.path`. No idea as to why it happens on your machine.

**Comment by mcepl** [comment]
I am on Linux, so there are Python packages which come with the distribution. That’s all. I guess it would be the same as saying “Python which comes as part of Mac OS X” (but which is actually kept up-to-date).

**Comment by karolyi** [comment]
can you tell which Python version do you use exactly, and if you use any specific PPA for it? I use deadsnakes, which is 
```
deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic main
```

**Comment by mcepl** [comment]
I am a maintainer of Python for SUSE, so I am using stock python3-3.7.3-1.2.x86_64.

**Comment by karolyi** [comment]
if that's the case, it might be that deadsnakes doesn't use the user local paths in `sys.path`.

summoning @asottile and @fkrull

**Comment by asottile** [comment]
I think you might be a bit confused: 

> I've installed this project with `pip install --user`, so I wouldn't have to install locally into all of my virtual envs I use.

virtual environments do not inherit system site packages (or user site packages) by default (they're intended to be completely isolated) -- you can use the `--system-site-packages` flag (though that ~kinda defeats most of the purpose of using virtualenvs in the first place)

To confirm the behaviour for `sys.path` here's the standard setup:

(I ran `docker run --rm -ti ubuntu:bionic` and then here's the history and command outputs)

### history

```console
root@7b35572fb90e:/# history
    1  apt update && apt install -y software-properties-common python3-pip
    2  add-apt-repository ppa:deadsnakes
    3  apt-get update
    4  apt-get install -y --no-install-recommends python3.7
    5  python3.6 -m pip install --user pre-commit
    6  python3.7 -m pip install --user pre-commit
    7  python3.6 -c 'import pprint, sys; pprint.pprint(sys.path)'
    8  python3.7 -c 'import pprint, sys; pprint.pprint(sys.path)'
```

### standard upstream debian `python3` (python3.6)

```console
root@7b35572fb90e:/# python3.6 -c 'import pprint, sys; pprint.pprint(sys.path)'
['',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/root/.local/lib/python3.6/site-packages',
 '/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages']
```

### deadsnakes python3.7

```console
root@7b35572fb90e:/# python3.7 -c 'import pprint, sys; pprint.pprint(sys.path)'
['',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/root/.local/lib/python3.7/site-packages',
 '/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages']
```

### conclusion

both deadsnakes and standard debian include the `.local` directory in `sys.path`

**Comment by karolyi** [comment]
hey @asottile,

does this also apply to `python3.7-minimal` (that actually contains the `python3.7` binary?

```
python3.7 -m venv venv
```

because after having a venv installed, this is what I get:

```
Python 3.7.4 (default, Sep  2 2019, 20:47:34)
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Could not open PYTHONSTARTUP
FileNotFoundError: [Errno 2] No such file or directory: '/home/karolyi/.pythonrc'
>>> import sys
>>> sys.path
['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/karolyi/Work/private/test/venv/lib/python3.7/site-packages']
```

that is, no included packages from ~/.local

**Comment by asottile** [comment]
I'll repeat since you missed it:

> I think you might be a bit confused:
> 
> > I've installed this project with pip install --user, so I wouldn't have to install locally into all of my virtual envs I use.
> 
> virtual environments do not inherit system site packages (or user site packages) by default (they're intended to be completely isolated)

**Comment by karolyi** [comment]
@mcepl if the case is the aforementioned one, you must be packaging your python wrong.

**Comment by mcepl** [comment]
@karolyi I am not, because I don’t use venv. And of course, I know about ``--system-site-packages`` and its rather controversial fame.

**Comment by karolyi** [comment]
I guess I'm closing this issue. Here are the takeaways:
- when using venv, one has to add their locals to `PYTHONPATH`
- system-wide python will use user locals

So the solution still stays the one I mentioned: Just add your `~/.local...` to `PYTHONPATH` when using venv.
