### ISSUE TITLE
pylint_lint.py returns existing diagnostics unless is_saved=True

### ISSUE THREAD

**Issue by casch-at** [palantir/python-language-server#603]
When I open a file I expect that the file gets linted with pylint, but `python_ls.py::m_text_document__did_open()` calls `self.lint` with `is_saved=False`. pylint_lint.py will return in that case the last diagnostics, which is empty after opening the file.

**Comment by ccordoba12** [comment]
Good catch! Could you submit a PR to fix that? Thanks!

**Comment by casch-at** [comment]
Sure!
