### ISSUE TITLE
Completions not working properly after Jedi 0.14.0

### ISSUE THREAD

**Issue by Aayush04** [palantir/python-language-server#606]
Yesterday, python released a new version of jedi 0.14.0. After this autocompletion not working properly. Getting the following error in messages:
`Language Client: Error: AttributeError: 'NoneType' object has no attribute 'full_name'
`

<img width="1217" alt="Screen Shot 2019-06-21 at 2 42 08 PM" src="https://user-images.githubusercontent.com/4752354/59912019-cc65a580-9432-11e9-8e39-fdb515ae087e.png">

But working fine on the last release i.e. Jedi 0.13.3

**Comment by ccordoba12** [comment]
Thanks for reporting. Please downgrade to Jedi 0.13.3 in the meantime.

I also just released 0.27.0 that prevents pulling Jedi 0.14 (until we fix this problem).

**Comment by ccordoba12** [comment]
@steff456, please take a look at this one.

**Comment by steff456** [comment]
I started the server with the master's version of jedi and the error is not present and the completions are working as expected. 

@Aayush04 you can test it by installing jedi with `pip install jedi git+https://github.com/davidhalter/jedi`
