### ISSUE TITLE
How does this server compare to the one developed by Microsoft

### ISSUE THREAD

**Issue by ianyepan** [palantir/python-language-server#617]
As titled, I am choosing between this python-language-server and the one maintained by Microsoft: (https://github.com/microsoft/python-language-server). I'd love to know the differences between these 2 implementations. Cheers!

**Comment by ccordoba12** [comment]
As far as I know, the Microsoft server is developed in C# and doesn't use Jedi for code completions, whereas this one is written in Python and uses Jedi.

**Comment by r3m0t** [comment]
The MS VS Code plugin uses the language server and some python libraries like isort and black. Their language server doesn't use any external Python projects.

**Comment by iago-lito** [comment]
Do both feature exactly the same functionality? Why would one pick one rather than the other?

**Comment by ccordoba12** [comment]
Microsoft decided to create a different server from scratch. You should ask them why.

**Comment by iago-lito** [comment]
Aw, harsh X'(  
Have you been in touch with them about this unfortunate event? Any chance to have both your efforts combined is some way?

**Comment by ccordoba12** [comment]
> Have you been in touch with them about this unfortunate event?

They're still using this server by default VSCode, if I understand things correctly. Users have to opt-in to use theirs.

But I think they didn't discussed why they wanted to create a new server. Probably to use their own technologies and have it under their control. 

> Any chance to have both your efforts combined is some way?

I doubt it because their server is done in C#, as I mentioned above.

**Comment by ianyepan** [comment]
@ccordoba12 Thanks for the reply, I've also asked a similar question on microsoft's github repo and got a semi-detailed response from one of their engineers: https://github.com/microsoft/python-language-server/issues/1284

Thought y'all might be interested.

FTR I'm sticking to this **palantir** one.

**Comment by gatesn** [comment]
Just to clarify, I’m not aware of any VSCode extension that makes use of this language server.

VSCode’s current Python extension is a client-side typescript wrapper that calls out to Jedi/Python for functionality.

The other interesting piece is that this language server is very extensible. It’s easy to add new methods to the LSP if you happen to also control the client.
