### ISSUE TITLE
Cannot Install pocketsphinx 

### ISSUE THREAD

**Issue by clh007x** [palantir/python-language-server#620]
I cannot install pocketsphinx 0.1.15 on mac
I get the following error message:
ERROR: Complete output from command /Users/CLH/tutorial_env/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/r4/xb7ypxxx7bvbfw4g2d257h800000gq/T/pip-install-4a9onnuh/pocketsphinx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/r4/xb7ypxxx7bvbfw4g2d257h800000gq/T/pip-record-236ohs84/install-record.txt --single-version-externally-managed --compile --install-headers /Users/CLH/tutorial_env/include/site/python3.7/pocketsphinx:
    ERROR: running install
    running build_ext
    building 'sphinxbase._sphinxbase' extension
    swigging deps/sphinxbase/swig/sphinxbase.i to deps/sphinxbase/swig/sphinxbase_wrap.c
    swig -python -modern -threads -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o deps/sphinxbase/swig/sphinxbase_wrap.c deps/sphinxbase/swig/sphinxbase.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Users/CLH/tutorial_env/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/r4/xb7ypxxx7bvbfw4g2d257h800000gq/T/pip-install-4a9onnuh/pocketsphinx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/r4/xb7ypxxx7bvbfw4g2d257h800000gq/T/pip-record-236ohs84/install-record.txt --single-version-externally-managed --compile --install-headers /Users/CLH/tutorial_env/include/site/python3.7/pocketsphinx" failed with error code 1 in /private/var/folders/r4/xb7ypxxx7bvbfw4g2d257h800000gq/T/pip-install-4a9onnuh/pocketsphinx/

Please help...

**Comment by ccordoba12** [comment]
This has nothing to do with this project, sorry.
