### ISSUE TITLE
Dependency on git

### ISSUE THREAD

**Issue by lilliesAndRoses** [palantir/python-language-server#622]
When the python language server is spawned, (say using the langserver_ext.py script in python-jsonrpc-server) on my macbook air, I get the prompt to install "git" as shown below.

![image](https://user-images.githubusercontent.com/19527338/61293657-d2f8fa00-a7f1-11e9-9d64-b3e238f74d09.png)

Why do I get this prompt and what can I change in my language server to suppress this? I do not need any version controlling support from the language server and this prompt is annoying me and users of my application.

**Comment by fheilz** [comment]
You need to install git as the error indicated. Click on install and follow the directions.

**Comment by fheilz** [comment]
@palantirtech Please close this issue.
