### ISSUE TITLE
No matching distribution found for python-lenguaje-server

### ISSUE THREAD

**Issue by alfoquial** [palantir/python-language-server#628]
Hello
Trying to install pyls get the error No matching distribution found for python-lenguaje-server
I have Fedora 30 with python 3.7.3
-> % pip3 install 'python-lenguaje-server'
Collecting python-lenguaje-server
ERROR: Could not find a version that satisfies the requirement python-lenguaje-server (from versions: none)
ERROR: No matching distribution found for python-lenguaje-server

What version of python is supported? According to the documentation 3.5+

Thanks

**Comment by ccordoba12** [comment]
> python-lenguaje-server

It's not `lenguaje`, it's `language`
