### ISSUE TITLE
Fails to run python3.7 - Syntax Error: invalid syntax print

### ISSUE THREAD

**Issue by ryanvade** [palantir/python-language-server#631]
I installed pyls with `pip install 'python-language-server[all]'` and then tried to run pyls and received the following:
```
~ 
➜ pyls
Traceback (most recent call last):
  File "/home/ryan/.local/bin/pyls", line 6, in <module>
    from pyls.main import main
  File "/home/ryan/.local/lib/python3.7/site-packages/pyls/main.py", line 65
    print '%s%s' % ('    ' * indent, name)
               ^
SyntaxError: invalid syntax
```

I have the following versions:
`python-language-server 0.28.1`
```
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
```

Do I need to use a newer version with python 3.7?

Side note, I'm trying to get this to work with Atom.

**Comment by med-merchise** [comment]
Run:
```sh
pip --version
```
My result is:
pip 19.2.1 from ~/.local/lib/python3.7/site-packages/pip (python 3.7)

Maybe you installed pyls with a Python 2 PIP.  In that case, use pip3, or pip3.7.

**Comment by ccordoba12** [comment]
> /home/ryan/.local/lib/python3.7/site-packages/pyls/main.py

There's no `pyls/main.py` file in this repo, so I don't know where's this error is coming from.

I'm closing this one because it looks like an installation issue.

**Comment by MarkGreeny** [comment]
I am having the same issue, with correct version of pip. Has anyone figured out how to fix this?

**Comment by yonilevy** [comment]
To anyone wondering, there's a new pip package conveniently name "[pyls](https://github.com/tartley/pyls)", which also outputs a `pyls` binary. Our mistake was pip installing `pyls`, overwriting our binary. To get it working, uninstall pyls, then reinstall python-language-server to get the binary back. I'd argue this project should try to take over the "pyls" name to avoid confusion.

**Comment by ccordoba12** [comment]
Thanks @yonilevy for pointing that out! That's the real cause of this problem.

**Comment by beyondpie** [comment]
@yonilevy 
Thanks a lot. You let me stay in python lsp for more time before I just want to quit.

**Comment by MituuZ** [comment]
@yonilevy 
Thank you for this.
