### ISSUE TITLE
Docs about vscode-client needs update

### ISSUE THREAD

**Issue by youben11** [palantir/python-language-server#632]
While setuping the vscode-client with pyls, I noticed that the steps defined in the README.md file found [here](https://github.com/palantir/python-language-server/tree/develop/vscode-client) aren't adapted to pyls. There is also some broken links.

**Comment by ccordoba12** [comment]
Pull requests to improve this are welcome.

**Comment by youben11** [comment]
will work on it shortly

**Comment by youben11** [comment]
updated here #633
