### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by m0caa** [palantir/python-language-server#641]
command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0XTPUw/websockets/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0XTPUw/websockets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-0XTPUw/websockets/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0XTPUw/websockets/setup.py", line 24, in <module>
        raise Exception("websockets requires Python >= 3.4.")
    Exception: websockets requires Python >= 3.4.

**Comment by ccordoba12** [comment]
This problem has nothing to do with this project, sorry.
