### ISSUE TITLE
Incorrect mention of tox to run test suite

### ISSUE THREAD

**Issue by youben11** [palantir/python-language-server#644]
Tox is a requirement for running the test suite, however, it's not listed in the setup.py and will not be installed when running `pip install .[test]`.

This was an issue when running test using the new Github Actions feature

**Comment by ccordoba12** [comment]
How are you trying to run the test suite? I mean, simply running

    pytest

in the root of the repo works fine for me.

**Comment by youben11** [comment]
in the readme it says that in order to run the test suite you have to run `pip install .[test] && tox` and doing this is what led me to the problem, is it an error with the doc?

**Comment by ccordoba12** [comment]
Yes. I think `tox` was used to run the test suite in several Python versions, but now that's taken care of in the matrix of the continuous integration services.

So please change that line in the Readme to be

    pip install .[test] && pytest

**Comment by youben11** [comment]
done #646
