### ISSUE TITLE
tests failing because of latest pylint release

### ISSUE THREAD

**Issue by youben11** [palantir/python-language-server#661]
Looks like the latest release of pylint is more precise with the column where the syntax error is.

### The test

We are testing pylint on the following document. (full code [here](https://github.com/palantir/python-language-server/blob/c3cab77a85b1de4af1aec1bafea6a7320d6baec5/test/plugins/test_pylint_lint.py))

```python
def hello()
    pass
```

pylint 2.3.1 reports back the 0 as the character where the syntax error is, however, pylint 2.4.1 is reporting back a 12 which is actually the exact location where a ':' must be introduced. 

The test is still expecting a value of 0 so the test fails.

**Comment by uschi2000** [comment]
yeah, let's get this fixed asap, @youben11

**Comment by youben11** [comment]
fixed #663
