### ISSUE TITLE
Overloads signature

### ISSUE THREAD

**Issue by AmjadHD** [palantir/python-language-server#664]
```python
@overload
def add(x: int, y:int) -> int: ...

@overload
def add(x: int, y: float) -> float: ...

def add(x, y):
    return x + y
```
can pyls be modified send multiple signatures in this case ?

**Comment by ccordoba12** [comment]
I don't understand what the current and expected behaviors are. Please clarify.

**Comment by joreiff** [comment]
He probably refers to https://docs.python.org/3/library/typing.html#typing.overload.

**Comment by AmjadHD** [comment]
I have three files located in one folder:
mod.py:
```python
def add(x, y):
    return x + y
```
mod.pyi:
```python
from typing import overload


@overload
def add(x: int, y: int) -> int: ...


@overload
def add(x: int, y: float) -> float: ...
```
and test.py:
```python
from mod import add


add(
```
when I type `add(` in test.py with sublime text, I get this signature help:
![image](https://user-images.githubusercontent.com/33235928/65966604-a6539680-e460-11e9-8545-f6588c2adbca.png)
this is sublime's [LSP](https://github.com/tomv564/LSP) log:
```
LSP:  --> textDocument/signatureHelp
LSP:      {'activeParameter': 0, 'signatures': [{'documentation': '', 'label': 'add(x: int, y: float) -> float', 'parameters': [{'documentation': None, 'label': 'x'}, {'documentation': None, 'label': 'y'}]}], 'activeSignature': 0}
```
you can see that `signatures` contains one signature only while it should contain two as described in the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_signatureHelp)
mypy does list all overloads, maybe you can use that:
![image](https://user-images.githubusercontent.com/33235928/65966683-bf5c4780-e460-11e9-8800-f76c9ac825a9.png)

**Comment by tomv564** [comment]
The spec says:
> There can be multiple signature but only one active and only one active parameter.

So it's an _option_, not a requirement to send multiple signatures.

Mypy is not the right tool for this, it is built for type checking entire documents, not "tell me about the thing on line 50" queries.

Jedi is the library used for signature help, and it did add support for stubs in a release last summer - I think they skipped support for overloads. See: https://github.com/davidhalter/jedi/issues/839

**Comment by AmjadHD** [comment]
> So it's an option, not a requirement to send multiple signatures.

yes I know it's an option this is a feature request not a bug report

> Jedi is the library used for signature help, and it did add support for stubs in a release last summer - I think they skipped support for overloads. See: davidhalter/jedi#839

so should this be opened in the jedi repo ?

**Comment by ccordoba12** [comment]
Yes. This can't be solved here.
