### ISSUE TITLE
Support pyenv virtualenv

### ISSUE THREAD

**Issue by 15cm** [palantir/python-language-server#670]
Signed the contributor license agreement. Still blocked in #657. Could anyone take a look at the PR?

**Comment by ccordoba12** [comment]
Closing because there's already a PR opened about this.

**Comment by 15cm** [comment]
Would you mind sharing the link of that PR? For pyenv support, I only see my PR though.

**Comment by ccordoba12** [comment]
I thought your PR implemented that support because it has the same title as this issue. So I don't see the point in leaving opened this issue.

**Comment by 15cm** [comment]
The reason I open this issue is that my PR have been blocked for 2 weeks by
the CI and want to know if I should just wait.

**Comment by ccordoba12** [comment]
It's not blocked by the CIs (CIs are green, actually). It's just that no one has had time to review it.

**Comment by 15cm** [comment]
I am just wondering if it is the case. Thanks for your update :)

**Comment by syphar** [comment]
@15cm how exactly does the PR solve this issue? 
Stumbled on it myself, and am trying to fit it.
