### ISSUE TITLE
Goto definition goes to the stub and not the actual implementation

### ISSUE THREAD

**Issue by AmjadHD** [palantir/python-language-server#675]
I many cases, when i execute goto definition on a symbol it goes to the stub file instead of the actual implementation
```python
import os.path

os.path.dirname(...)
```
Invoke goto definition on `dirname`
it opens up the symbol location in "...\python\python37\lib\site-packages\jedi\third_party\typeshed\stdlib\2and3\ntpath.pyi"
while it should open "...\Python\Python37\Lib\ntpath.py"

**Comment by gatesn** [comment]
This sounds like something to file against Jedi (@davidhalter) since we just call goto_assignments: https://github.com/palantir/python-language-server/blob/8db7654f9c3786f579416ec42e6a6625003ee43a/pyls/plugins/definition.py#L11

**Comment by ccordoba12** [comment]
Closing because this was reported upstream.

**Comment by davidhalter** [comment]
BTW if someone else is experiencing this, please report it here: https://github.com/davidhalter/jedi/issues/1423

I cannot reproduce it. So it's pretty hard to fix it.
