### ISSUE TITLE
flake8: error: no such option: --maxLineLength

### ISSUE THREAD

**Issue by sh4nks** [palantir/python-language-server#678]
Hi, I am getting following error when trying to use the flake8 integration:

```
1:1   	flake8      	error     	Usage: flake8 [options] file file ...
             	            	          	
     	            	          	flake8: error: no such option: --maxLineLength
```

When I remove the option ``max-line-length = 80`` from the ``setup.cfg`` the error disappears but it isn't really the solution for my problem as I'd like to check the line length as well :-)

System info:
- flake8 3.7.8
- python-language-server 0.29.1
- Python 3.7.4

**Comment by youben11** [comment]
From where did you get this output? flake8 integration isn't using the flake8 utility for the moment and shouldn't be showing the "Usage". Please provide more information about how to reproduce.

**Comment by sh4nks** [comment]
Sorry, I probably should have mentioned that I am using pyls on Sublime Text 3 with the [LSP](https://github.com/tomv564/LSP) extension.

**Comment by youben11** [comment]
There is something else running the flake8 command, pyls shouldn't be doing that.

**Comment by sh4nks** [comment]
Sorry for my late reply, I wasn't able to get back to it earlier. I have turned on the pyls logging capabilities to see if it's caused by pyls or not.. but unfortunately it is caused by pyls: https://gist.github.com/sh4nks/a238fffdc8258d929e2a369ab7de5fee

If you scroll to the bottom of the log file you can see the error which is caused by pyls (or search for ``--maxLineLength``).

Edit:
I can reproduce this error in this (python-language-server) repository as well by adding a new section:
```ini
[flake8]
max-line-length = 80
```
to the ``setup.cfg`` file.

**Comment by ccordoba12** [comment]
@youben11, I think this was fixed in your last PR, right?

**Comment by youben11** [comment]
No @ccordoba12, this one is not really related to pyls, as I saw from the log that the pyls's flake8 plugin is generating diagnostics that shouldn't be returned at all. @sh4nks you should be probably using another python library which is interfering with pyls.

**Comment by sh4nks** [comment]
So, this is actually kinda funny - while googling for a solution I stumpled upon my very own issue.
However, now I know what causes the error.
It's the pyls-flake8 plugin -- especially this line: https://github.com/emanspeaks/pyls-flake8/blob/master/pyls_flake8/plugin.py#L90.
