### ISSUE TITLE
Cache jedi scripts between hooks

### ISSUE THREAD

**Issue by gatesn** [palantir/python-language-server#68]

**Comment by gatesn** [comment]
JediScript contains position, therefore not sensibly cacheable between hooks

**Comment by lgeiger** [comment]
> JediScript contains position, therefore not sensibly cacheable between hooks

👍 
This would require a change in Jedi. `.completions()`, `.goto_assignment()` and others would need to accept the position arguments.
Would the effort be worthwhile the performance gain?
