### ISSUE TITLE
Deeptools error - Solving environment: failed with initial frozen solve

### ISSUE THREAD

**Issue by Dia-dev** [palantir/python-language-server#686]
Hi,

I am currently doing an ATAC-seq analysis for a bioinformatics course, but I am a python beginner and I am having trouble navigating it. I have 6 sorted bam files and my instructions say to use deeptools to assess the correlation between them (multiBamSummary -> plotCorrelation) and also check how much of the genome is covered and at what depth (plotCoverage).

I have been trying to install deeptools on Anaconda2 prompt (both on Python 3.7 and 2.7 versions) following this tutorial: https://deeptools.readthedocs.io/en/develop/content/installation.html First I had an environment error that I solved with the code below, but now I get other errors and I can not find a solution online? I tried uninstalling and reinstalling anaconda and other packages, but it does not work.

The code that I used: conda create --name dianaenv python=2.7 conda activate dianaenv conda config --add channels bioconda conda install -c bioconda deeptools

The error: Collecting package metadata (current_repodata.json): done Solving environment: failed with initial frozen solve. Retrying with flexible solve. Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source. Collecting package metadata (repodata.json): done Solving environment: failed with initial frozen solve. Retrying with flexible solve. Solving environment: / Found conflicts! Looking for incompatible packages. This can take several minutes. Press CTRL-C to abort.- failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package vs2008_runtime conflicts for: python=2.7 -> vs2008_runtime Package sqlite conflicts for: python=2.7 -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.30.1,<4.0a0'] Package pysam conflicts for: deeptools -> pysam[version='>=0.14.0'] Package vc conflicts for: python=2.7 -> vc[version='9.*|>=9,<10.0a0'] Package deeptoolsintervals conflicts for: deeptools -> deeptoolsintervals[version='>=0.1.8'] Package matplotlib conflicts for: deeptools -> matplotlib[version='>=2.1.1|>=3.0.0'] Package pybigwig conflicts for: deeptools -> pybigwig[version='>=0.2.3'] Package ca-certificates conflicts for: python=2.7 -> ca-certificates Package scipy conflicts for: deeptools -> scipy[version='>=0.17.0'] Package py2bit conflicts for: deeptools -> py2bit[version='>=0.2.0'] Package plotly conflicts for: deeptools -> plotly[version='>=1.9.0|>=2.0.0'] Package pip conflicts for: python=2.7 -> pip Package numpy conflicts for: deeptools -> numpy[version='>=1.9.0'] Package pandas conflicts for: deeptools -> pandas

I also tried to install the requirements individually and installing numpy scipy and matplotlib works fine but when I try to install py2bit, pybigwig or pysam, I also get errors:

pip install py2bit DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support Collecting py2bit Using cached https://files.pythonhosted.org/packages/53/bb/547a927bed736ead3dc909e1e552d57c9034bb9493eff80544c0cf6e4828/py2bit-0.3.0.tar.gz Building wheels for collected packages: py2bit Building wheel for py2bit setup.py) ... error ERROR: Command errored out with exit status 1: command: 'C:\Users\User\Anaconda2\envs\dianaenv\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\users\user\appdata\local\temp\pip-install-6nxreu\py2bit\setup.py'"'"'; __file__='"'"'c:\users\user\appdata\local\temp\pip-install-6nxreu\py2bit\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'c:\users\user\appdata\local\temp\pip-wheel-vrkfci' --python-tag cp27 cwd: c:\users\user\appdata\local\temp\pip-install-6nxreu\py2bit\ Complete output (21 lines): C:\Users\User\Anaconda2\envs\dianaenv\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'classifier' warnings.warn(msg) running bdist_wheel running build running build_py creating build creating build\lib.win-amd64-2.7 creating build\lib.win-amd64-2.7\py2bitTest copying py2bitTest\test.py -> build\lib.win-amd64-2.7\py2bitTest copying py2bitTest__init__.py -> build\lib.win-amd64-2.7\py2bitTest running egg_info writing py2bit.egg-info\PKG-INFO writing top-level names to py2bit.egg-info\top_level.txt writing dependency_links to py2bit.egg-info\dependency_links.txt reading manifest file 'py2bit.egg-info\SOURCES.txt' reading manifest template 'MANIFEST.in' writing manifest file 'py2bit.egg-info\SOURCES.txt' copying py2bitTest\foo.2bit -> build\lib.win-amd64-2.7\py2bitTest running build_ext building 'py2bit' extension error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27

ERROR: Failed building wheel for py2bit Running setup.py clean for py2bit Failed to build py2bit Installing collected packages: py2bit Running setup.py install for py2bit ... error ERROR: Command errored out with exit status 1: command: 'C:\Users\User\Anaconda2\envs\dianaenv\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\users\user\appdata\local\temp\pip-install-6nxreu\py2bit\setup.py'"'"'; __file__='"'"'c:\users\user\appdata\local\temp\pip-install-6nxreu\py2bit\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\user\appdata\local\temp\pip-record-xmdylh\install-record.txt' --single-version-externally-managed --compile cwd: c:\users\user\appdata\local\temp\pip-install-6nxreu\py2bit\ Complete output (21 lines): C:\Users\User\Anaconda2\envs\dianaenv\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'classifier' warnings.warn(msg) running install running build running build_py creating build creating build\lib.win-amd64-2.7 creating build\lib.win-amd64-2.7\py2bitTest copying py2bitTest\test.py -> build\lib.win-amd64-2.7\py2bitTest copying py2bitTest__init__.py -> build\lib.win-amd64-2.7\py2bitTest running egg_info writing py2bit.egg-info\PKG-INFO writing top-level names to py2bit.egg-info\top_level.txt writing dependency_links to py2bit.egg-info\dependency_links.txt reading manifest file 'py2bit.egg-info\SOURCES.txt' reading manifest template 'MANIFEST.in' writing manifest file 'py2bit.egg-info\SOURCES.txt' copying py2bitTest\foo.2bit -> build\lib.win-amd64-2.7\py2bitTest running build_ext building 'py2bit' extension error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27 ---------------------------------------- ERROR: Command errored out with exit status 1: 'C:\Users\User\Anaconda2\envs\dianaenv\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\users\user\appdata\local\temp\pip-install-6nxreu\py2bit\setup.py'"'"'; __file__='"'"'c:\users\user\appdata\local\temp\pip-install-6nxreu\py2bit\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\user\appdata\local\temp\pip-record-xmdylh\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

Also, if I try to use pip install I get a matplotlib error: pip install --user deeptools DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support Collecting deeptools Using cached https://files.pythonhosted.org/packages/82/8e/d9d4b66b2ce1bd48f1db43357c8eb019ae3e8bb1bb7a9e82667db981e1df/deepTools-3.3.1.tar.gz Collecting numpy>=1.9.0 Downloading https://files.pythonhosted.org/packages/48/83/203c397ecec78bdd618a0fb04a47482cfa2ae5ea2c6d428ed94258fe8671/numpy-1.16.5-cp27-cp27m-win_amd64.whl (11.9MB) |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 11.9MB 2.5MB/s Collecting scipy>=0.17.0 Downloading https://files.pythonhosted.org/packages/49/73/22e125f335986fdc3b03c09cdf8ffe0d9d5471eec301aeb2e33db78b3e7f/scipy-1.2.2-cp27-cp27m-win_amd64.whl (30.5MB) |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 30.5MB 187kB/s ERROR: Could not find a version that satisfies the requirement matplotlib>=3.0.0 (from deeptools) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4) ERROR: No matching distribution found for matplotlib>=3.0.0 (from deeptools)

**Comment by ccordoba12** [comment]
Your error has nothing to do with this project.

As a side note, your using Anaconda but using pip to install packages that can be installed with conda. That's a recipe for disaster because the two of them are incompatible.
