### ISSUE TITLE
syntax error when starting pyls

### ISSUE THREAD

**Issue by rwols** [palantir/python-language-server#716]
I get this syntax error when starting pyls:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyls", line 6, in <module>
    from pyls.main import main
  File "/usr/local/lib/python3.7/site-packages/pyls/main.py", line 65
    print '%s%s' % ('    ' * indent, name)
               ^
SyntaxError: invalid syntax
```

macOS 10.15, Python 3.7.2 installed via homebrew, pyls 0.1.6

**Comment by goanpeca** [comment]
Yikes that print should have parens

**Comment by ccordoba12** [comment]
> pyls 0.1.6

I guess you incorrectly installed the wrong package:

https://pypi.org/project/pyls/

This package's name is `python-language-server`.

**Comment by rwols** [comment]
OMG that was the problem! Thanks @ccordoba12

**Comment by SarveshMD** [comment]
> > pyls 0.1.6
> 
> I guess you incorrectly installed the wrong package:
> 
> https://pypi.org/project/pyls/
> 
> This package's name is `python-language-server`.

Thanks a lot !!!
It helped
