### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by duddud2912** [palantir/python-language-server#736]
I tried to install "pip install kss", and shows this error. 

 `ERROR: Command errored out with exit status 1:
     command: 'c:\users\krm\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\ESTsoft\\CreatorTemp\\pip-install-j9wgmocf\\kss\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\ESTsoft\\CreatorTemp\\pip-install-j9wgmocf\\kss\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-j9wgmocf\kss\pip-egg-info'
         cwd: C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-j9wgmocf\kss\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-j9wgmocf\kss\setup.py", line 31, in <module>
        extra_compile_args=extra_compile_args,
    NameError: name 'extra_compile_args' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output`

How can I solve this error?

**Comment by shrutiichandra** [comment]
i also get similar error when trying to install ncvx: pip install ncvx
 ERROR: Command errored out with exit status 1:
     command: 'c:\users\chand\downloads\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chand\\AppData\\Local\\Temp\\pip-install-ef9vdg29\\cyscs\\setup.py'"'"'; __file__='"'"'C:\\Users\\chand\\AppData\\Local\\Temp\\pip-install-ef9vdg29\\cyscs\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\chand\AppData\Local\Temp\pip-record-mpmho6eg\install-record.txt' --single-version-externally-managed --compile

**Comment by ccordoba12** [comment]
> i also get similar error when trying to install ncvx

This has nothing to do with this project.

**Comment by ccordoba12** [comment]
> I tried to install "pip install kss", and shows this error.

Neither does this.
