### ISSUE TITLE
Not work well with LanguageClient-neovim

### ISSUE THREAD

**Issue by clouduol** [palantir/python-language-server#738]
First, I install python-language-server with the command `pip install 'python-language-server[all]'`.

Then, I install LanguageClient-neovim using vim-plug according to [https://github.com/autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim), and update the plug to latest version(2020/1/29).

Here is the configuration:
```
" LanguageClient-neovim
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'zsh install.sh',
    \ }

" Required for operations modifying multiple buffers like rename.
set hidden

let g:LanguageClient_serverCommands = {
    \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],
    \ 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
    \ 'javascript.jsx': ['tcp://127.0.0.1:2089'],
    \ 'python': ['/usr/local/bin/pyls'],
    \ 'ruby': ['~/.rbenv/shims/solargraph', 'stdio'],
    \ 'swift': ['sourcekit-lsp'],
    \ 'c': ['ccls'],
    \ 'c++': ['ccls'],
    \ }

nnoremap <F5> :call LanguageClient_contextMenu()<CR>
" Or map each action separately
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> gb <C-o>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
```

But when I open a .py file and have a try, I get the following error:
`Error: Failure { jsonrpc: Some(V2), error: Error { code: InvalidParams, message: ...    doc = workspace.get_document(doc_uri) if doc_uri else None\n")])})) }, id: Num(2)`

This is happened when I use rename, goto definition, hover and other functions.

What should I do?

**Comment by mpanarin** [comment]
This looks like an issue with the client. Better to open an issue on their side.

**Comment by ccordoba12** [comment]
Agreed. Closing then.

**Comment by clouduol** [comment]
> This looks like an issue with the client. Better to open an issue on their side.

But the client works well with ccls and rls...

**Comment by mpanarin** [comment]
@guoyunlong16 
```
Error: Failure { jsonrpc: Some(V2), error: Error { code: InvalidParams, message: ... doc = workspace.get_document(doc_uri) if doc_uri else None\n")])})) }, id: Num(2)
```
Error says that pyls recieved invalid json. So this is definitely client configuration error.
Not to say that there is a bunch of other clients that work with pyls perfectly fine )

**Comment by syphar** [comment]
@guoyunlong16 , cc @mpanarin 

I had the same error, strangely after upgrading my virtualenv where I keep `python-language-server`. 

I found out it's actually related to the `jedi` version. I did upgrade the whole virtualenv, including jedi to `0.16.0`. Only saw later that that version is marked as incompatible for `pyls`. 

So downgrading `jedi` to the last version (`0.15.2`) actually fixed this error.

**Comment by clouduol** [comment]
> @guoyunlong16 , cc @mpanarin
> 
> I had the same error, strangely after upgrading my virtualenv where I keep `python-language-server`.
> 
> I found out it's actually related to the `jedi` version. I did upgrade the whole virtualenv, including jedi to `0.16.0`. Only saw later that that version is marked as incompatible for `pyls`.
> 
> So downgrading `jedi` to the last version (`0.15.2`) actually fixed this error.

I used `zchee/deoplete-jedi` for python completion, which dependes on `jedi`. I changed the `jedi` version to `v0.15.2` used by ` zchee/deoplete-jedi`, but it still failed to work. Now I have no idea about this problem.

**Comment by syphar** [comment]
@guoyunlong16 your error-report (and my usecase) was about a possible problem with `python-language-server`. If you are using a language-server, there is actually no need to use `deoplete-jedi`, since `python-language-server` uses `jedi` the background anyways, and also `LanguageClient-Neovim` integrates well into `deoplete` on its own.
