### ISSUE TITLE
`python -m pyls --help` fails

### ISSUE THREAD

**Issue by dpensi** [palantir/python-language-server#739]
on fedora 31 if i run the command
```
python -m pyls --help
```
i receive the following output:

```
/usr/bin/python: No module named pyls.__main__; 'pyls' is a package and cannot be directly executed
```

**Comment by ccordoba12** [comment]
This happens because you installed the pyls module:

https://pypi.org/project/pyls/

The name of this package is `python-language-server`.

**Comment by dpensi** [comment]
Hi @ccordoba12, Thanks but I don't understand. I'm basically try to use the language server in atom and it's not working; following their readme (https://github.com/lgeiger/ide-python/blob/master/README.md) they state to run 
```
python -m pip install 'python-language-server[all]'
````
and then
```
python -m pyls --help
```
to check everything is working (in my case it's not)

what do you mean by 'The name of this package is python-language-server.'?
