### ISSUE TITLE
Adapt to the last Jedi

### ISSUE THREAD

**Issue by sunlin7** [palantir/python-language-server#744]
Hi,
Error happend with fresh installed python-language-server.
After check the error message, it cause by incompatable dependency that python-language-server depend on 0.14<=JEDI<0.16, while the pip actually install the last JEDI (0.16.0) when install pyls.

The workaround is change the setup.py to depend on JEDI 0.15.2.

Is there any plan to cachup with last JEDI (0.16.*)?

Thanks

The JEDI releases are:
https://github.com/davidhalter/jedi/releases

**Comment by stonebig** [comment]
another option would be python-language-server to vendors jedi.

**Comment by wy-z** [comment]
```
ERROR: python-language-server 0.31.8 has requirement jedi<0.16,>=0.14.1, but you'll have jedi 0.16.0 which is incompatible.
ERROR: python-language-server 0.31.8 has requirement ujson<=1.35; platform_system != "Windows", but you'll have ujson 2.0.0 which is incompatible.
ERROR: python-jsonrpc-server 0.3.4 has requirement ujson<=1.35; platform_system != "Windows", but you'll have ujson 2.0.0 which is incompatible.
```

**Comment by hrehfeld** [comment]
Status? pyls is broken on archlinux.

**Comment by ccordoba12** [comment]
It's not our problem that upstream maintainers are not respecting our declared dependencies.

So instead of complaining here (because we're doing our job correctly), please inform this problem to your Linux distro.

**Comment by hrehfeld** [comment]
Sorry, but I didn't complain. I asked about the status of this issue and provided (hopefully valuable) info about problems larger parts of your userbase might run into. Next time, it'd be advisable to [check the bugtracker ](https://bugs.archlinux.org/?project=5&string=python-language-server)of the distro you complain about before scolding your users. 

What's the status on this issue?

PS. arch workaround by simply  downgrading jedi: ` pacman -U /var/cache/pacman/pkg/python-jedi-0.15.*-any.pkg.tar.xz`

**Comment by ccordoba12** [comment]
> What's the status on this issue?

Let me put it this way then: there's nothing for us to solve yet (and as I said before, it's not our fault that the PyLS is broken in Arch) because we're are declaring our dependency on Jedi correctly:

https://github.com/palantir/python-language-server/blob/143d9931cd0cabe92e1370b344cb02c406e0b0f1/setup.py#L38

So if that constraint is not respected by Arch maintainers, there's nothing we really need to do about it here, and you have to inform them that they introduced the breakage by not respecting it.

> Next time, it'd be advisable to check the bugtracker of the distro you complain about before scolding your users.

I'm sorry but you're the Arch user and the one with this problem. So it's up to you to find out if the problem is reported in your distro or not. And also to find the solution you posted above.

----

Finally, and going directly to the point, we'll try to update to Jedi 0.16 in the coming months, but there's no firm plan to do it yet.

**Comment by sunlin7** [comment]
@ccordoba12 Thank you for your information, there're workarounds for pip/pacman.
Looking forward pyls migrating to the last jedi.

**Comment by stonebig** [comment]
yesterday (march 20th) python-vscode extension moved to jedi-0.16 .0 https://devblogs.microsoft.com/python/python-in-visual-studio-code-march-2020-release/ , so I suppose python-langage-server will have to move soon, and couldn't move before

... also not a field of roses on Windows / Python-3.8 https://github.com/microsoft/vscode-python/issues/10357

**Comment by hrehfeld** [comment]
Thanks for the status update and taking care of this!

> I'm sorry but you're the Arch user and the one with this problem. So it's up to you to find out if the problem is reported in your distro or not. And also to find the solution you posted above.

That's what I did before posting, but I was interested on the status of migrating to jedi 0.16 nonetheless.

**Comment by ccordoba12** [comment]
@stonebig, thanks for the info but the VSCode extension stopped using this project a long time ago.

@hrehfeld, thanks for understanding and sorry if I was too blunt yesterday with my first answer. I was under a lot of stress.

**Comment by stonebig** [comment]
to the best of my experiment, there is no apparent issue for basic Spyder-4.1.1 with Jedi-0.16.0.

**Comment by ccordoba12** [comment]
That doesn't mean the test suite here and ours are passing.

**Comment by stonebig** [comment]
sure, my environment is a big deviation from Spyder officially supported packages: PyQt5-5.14.1, Parso-0.6.2, Jedi-0.16.0. I will try to deviate up to Jedi-1.0, Pyside2-5.15

**Comment by Foxboron** [comment]
I started hacking a bit on python-language-server to try and bridge the gap, but python-language-server requires some refactoring to work with the new API.

The main challenge is that `get_signatures()` can return multiple signatures for one definition. But pyls is currently structured around the assumption that only one signature is returned from each definition.

```python
@hookimpl
def pyls_completions(config, document, position):
   # ....
    return [_format_completion(d, include_params) for d in definitions] or None
```

So this is a bit problematic if the goal is to keep things backwards compatible with older versions of jedi, and makes it even weirder that they introduce this in an minor version update. There is also more deprecations coming in `0.17` with the Script API.

**Comment by Foxboron** [comment]
Test suite is currently hitting a bug with the pandas completion, tracking it upstream; https://github.com/davidhalter/jedi/issues/1529

**Comment by ccordoba12** [comment]
> So this is a bit problematic if the goal is to keep things backwards compatible with older versions of jedi

Thanks for helping us to take a look at this. There's no need to maintain compatibility with older Jedi versions.

> and makes it even weirder that they introduce this in an minor version update

We were already thinking to bump our version to 1.0, so we could take the chance to pair that with an update to Jedi 0.16.

**Comment by ccordoba12** [comment]
> sure, my environment is a big deviation from Spyder officially supported packages: PyQt5-5.14.1, Parso-0.6.2, Jedi-0.16.0. I will try to deviate up to Jedi-1.0, Pyside2-5.15

Then (I'm sorry to say it) we'll detect if we're running under WinPython and direct bugs reported in Spyder's issue tracker your way (I already did it with one person, thanks to your comment here).

If you want to go so far away from our declared dependencies is fine, but that will basically make WinPython an unsupported platform for Spyder (sorry).

**Comment by Foxboron** [comment]
I'll be tracking changes in a fork for the time being. Should be noted that it's being tested against the jedi master branch. https://github.com/Foxboron/python-language-server

Currently facing issues where property completion in the jedi test suite is returned as NoneTypes with no clear reason why. Probably need to be digging a bit deeper how this works.
`<BaseSignature full_name='builtins.NoneType', description='instance NoneType'>`

**Comment by bnavigator** [comment]
> Currently facing issues where property completion in the jedi test suite is returned as NoneTypes with no clear reason why. Probably need to be digging a bit deeper how this works.
> `<BaseSignature full_name='builtins.NoneType', description='instance NoneType'>`

@Foxboron my PR https://github.com/dalthviz/python-language-server/pull/1  to #775 resolves that. The trick is to look up the correct signature properties as a replacement for the deprecated `.param`  property, instead of using the signature as replacement for the `completion` object, so that it can be properly formatted in the way pyls wants to have it.

**Comment by stonebig** [comment]
Hi @bnavigator ,  how is it going with Jedi-0.17.0 ? Do we need to wait for Jedi-0.17.1  to retry the experiment ?

**Comment by bnavigator** [comment]
Hi,

I updated my setup to Jedi 0.17.0 and I am currently in the process of adding more changes to the PR dalthviz#1 to #775, because some more unit tests started to fail. Making good progress, but won't be able to continue in the next few hours. Have a look at the intermediate commit if you want.

**Comment by bnavigator** [comment]
Except for `test_missing_message`, which crashes the jsonrpc server at teardown of the test (not related to Jedi, I guess) my package now builds with #775 and dalthviz#1 applied:
https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python/python-python-language-server

To test it on the CI here, either @dalthviz or @ccordoba12 need to accept dalthviz#1 or I could open a new PR from the [bnavigator:jedi](https://github.com/bnavigator/python-language-server/tree/jedi) branch into palantir:develop

**Comment by ccordoba12** [comment]
@bnavigator, please open a PR from your own fork, but only updating the Jedi requirement, not the ujson one (that needs to be done in a different PR).

**Comment by bnavigator** [comment]
See #781, the ujson unpin was never included.
