### ISSUE TITLE
Using pylint only runs once during a workspace session

### ISSUE THREAD

**Issue by vakker** [palantir/python-language-server#747]
I'm planning to switch to pylint from pyflake using Emacs.
With pylint the file is only linted once (when I open it) and when I start editing all the errors and warnings disappear and Emacs reports 0 issues.

What could cause this and how to debug this further?

**Comment by goanpeca** [comment]
>I'm planning to switch to pylint from pyflake using Emacs.
With pylint the file is only linted once (when I open it) and when I start editing all the errors and warnings disappear and Emacs reports 0 issues.

Pylint takes much longer, so maybe you need to wait a bit before the results appear?

**Comment by vakker** [comment]
No, I did wait long enough.
The issue was that flycheck was also calling pylint for some reason which caused some interference.
