### ISSUE TITLE
Support for mypy checking as well (i.e typing)

### ISSUE THREAD

**Issue by mikn** [palantir/python-language-server#76]
Other lint-runners (like ALE and neomake) supports having mypy as a linter as well, which uses the typing library in stdlib and type annotations to verify optional static typing. It would be nice to have that support in python-language-server as well. :)

**Comment by gatesn** [comment]
@mikn Agree mypy would be a nice addition. But given mypy is Python 3 only (to run the type checking at least) I would recommend creating a plugin.

Happy to help out with this if you wanted to kick on off? Essentially you'll need to create a 'pyls' entry point. See https://pluggy.readthedocs.io for more information, and see `pyls/hookspecs.py` for information on which hooks you can implement. 

The built-in functionality is implemented as plugins as well so you can see how those are created.

**Comment by mikn** [comment]
Right! I made a rough pull request! I just want to clarify: mypy runs very well on Python 2 as well. If you want to go hard core, there's a typing package on pypi (https://pypi.python.org/pypi/typing) for 2.7+. I do not think there's a problem to leave this active in most cases as even without the typing library, it will try to do type inference for you and warn you of 'dict does not have append' etc. :)

**Comment by gatesn** [comment]
Although MyPy can type check Python 2 (though it does requires the --py27 flag or something like that) Im pretty sure it still requires Python 3 to run.

If you writing a small test for this, I imagine it will fail the py27 test suite but pass the py34.

If this is not the case, then great! Will be happy to merge after some tests. If it is the case, I'd recommend creating a new repo for this plugin. Then users can choose whether or not to install it (and hence require Python 3).



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by emmatyping** [comment]
Mypy has a runtime requirement of Python 3.3+, but can typecheck Python 2.7 & 3.3+.

**Comment by gatesn** [comment]
Right, in which case, I don't want to bump the Python dependency of pyls, so let's move it into another repository that depends on this one.

**Comment by tomv564** [comment]
Are you suggesting creating a new `python3-language-service` package?

I took the branch from the PR, rebased it and and added version requirements so mypy functionality is optional: https://github.com/palantir/python-language-server/compare/develop...tomv564:mypy_lint

Tox installs and tests pass (with coverage on mypy_lint only on python 3.2 or better)
@gatesn: Would this solution be workable?
@mikn: Do you want a PR against your branch so we can use the existing PR?

**Comment by gatesn** [comment]
No, I mean create a new repository entirely called e.g. "pyls-mypy". Then in setup.py, create an entry point:

```
    entry_points={
        'pyls': [
            'pyls_mypy = pyls_mypy.plugin',
        ],
    },
```

Then in plugin.py:

```
from pyls import hookimpl

@hookimpl
def pyls_lint(document):
    return [{
        'range': {...},
        'message': "The linting message to include",
        'source': 'mypy'
    }]
```

Then also in the setup.py, take a dependency on python-language-server and Python >= 3

**Comment by gatesn** [comment]
Then as long as it's installed in the same environment, pyls will pick up the plugin.

**Comment by tomv564** [comment]
Thanks for explaining, I found pluggy's `load_setuptools_entrypoints` feature now.
I'll have a look, or perhaps @mikn did some of this work already!

**Comment by tomv564** [comment]
Mypy plugin now lives at https://github.com/tomv564/pyls-mypy.
It is not published yet, would appreciate testing / comments before I do!

**Comment by tomv564** [comment]
Package is now published as `pyls-mypy`

**Comment by gatesn** [comment]
Awesome, thanks for this! Just need a nicer way to disable pyflakes / pep8 in favour of this now.

**Comment by ghost** [comment]
FYI pyflakes/pep8 and mypy are completely different creatures. Mypy is static typing, no overlap with any of the other linters.

**Comment by gatesn** [comment]
You're right... not sure what I was thinking there

**Comment by gatesn** [comment]
Closing since https://pypi.python.org/pypi/pyls-mypy/0.1.2 exists
