### ISSUE TITLE
Please update setup tools `pip install -U setuptools`

### ISSUE THREAD

**Issue by nna-bru** [palantir/python-language-server#764]
Please update setup tools `pip install -U setuptools`

_Originally posted by @gatesn in https://github.com/palantir/python-language-server/issues/370#issuecomment-395463397_

 import git
    ModuleNotFoundError: No module named 'git'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ccordoba12** [comment]
I don't understand what's the problem here.

**Comment by nna-bru** [comment]
When I try install some libs, my traceback shows this error message. I try install git, but this error persists.

**Comment by ccordoba12** [comment]
Your error is not related to this package, sorry.

**Comment by ccordoba12** [comment]
And I really don't know where it's coming from.
