### ISSUE TITLE
What LSP configuration options are supported?

### ISSUE THREAD

**Issue by dbarnett** [palantir/python-language-server#765]
Is there a reference page anywhere about what settings python-language-server will recognize in LSP configuration? The README mentions two options, `pyls.configurationSources` and `pyls.plugins.pydocstyle.enabled`, and I've found no other info about it.

**Comment by goanpeca** [comment]
See https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json

**Comment by ccordoba12** [comment]
Yep, that's it.

**Comment by dbarnett** [comment]
Consider adding a pointer to that in the README and/or any other form of help docs you have.

**Comment by ccordoba12** [comment]
Please create a pull request for that.

**Comment by dbarnett** [comment]
Alright, I hit some kind of CLA snag on my one-line README change, but I sent it and I think the CLA via Google should be good to go...
