### ISSUE TITLE
Application of incremental text changes is not atomic?

### ISSUE THREAD

**Issue by rwols** [palantir/python-language-server#793]
In SublimeText we have this "format on save" feature. When it is enabled, and when the document is saved by the user, a textDocument/didChange is notified, and immediately after a textDocument/formatting is requested.

It can sometimes happen that pyls returns text edits that destroy / chop up my python file.

I'm looking at the code in pyls and it looks like a thread pool of some sort is used to handle requests and notifications. The textDocument/didChange must be atomic in this case, i.e. other requests/notifications must wait for the handler for textDocument/didChange to finish. I'm unsure whether I'm looking in the right corner of the codebase.

**Comment by goanpeca** [comment]
>textDocument/didChange must be atomic in this case

I think that goes against how the LSP is specified?

@andfoy what do you think?

**Comment by rwols** [comment]
But it mostly worked when we didn't yet have incremental text sync. I guess in that case there's a single swap between the old text and the new text. In python that's basically atomic due to the GIL.

The spec indeed says that notification handling and request handling may be out of order, but a language server should of course handle incremental text sync asap.

**Comment by andfoy** [comment]
@rwols I think this is a problem indeed with race conditions that may affect requests that alter the text, such as formatting. I'll take a look at it
