### ISSUE TITLE
Signature and hover feature do not work when using virutal environment

### ISSUE THREAD

**Issue by binzhang-u5f6c** [palantir/python-language-server#794]
Hi!
I use `venv` to manage my packages. I don't want to install pyls in each virtual environment. I found feature in #680 works for me. I add my virtual environment via `jedi.environment` in my config file. The completion feature work well. However, I cannot get any signature help or hover information. These features work well for packages not installed in virtual environment.

My configuration looks like:

```
"pyls": {
    "plugins": {
        "jedi.environment": "/absolute/path/to/my/venv/directory"
    }
}
```

* OS: Arch Linux
* editor: neovim v0.4.3
* lsp client: coc.nvim v0.0.78
* pyls v0.31.10

**Comment by goanpeca** [comment]
@binzhang-u5f6c will need to check what might be the issue. Thanks for reporting.

**Comment by binzhang-u5f6c** [comment]
Hi @goanpeca !

I found the problem. There is a conflict between my user configuration file and workspace one. The completion feature looked as normal just because the TabNine gave the correct choice. After I solved the conflict, everything works well.

Sorry for bothering you.

**Comment by goanpeca** [comment]
Glad to know you found the issue! No bother at all !
