### ISSUE TITLE
Does pyls need to sit in the virtualenv of the project?

### ISSUE THREAD

**Issue by halloleo** [palantir/python-language-server#795]
I am trying out `pyls` (with Emacs' `lsp-mode`). 

In a project with a with virtualenv which contains pandas , `pyls` does not give me any completions on pandas.

I have installed `pyls` in its own virtual env and  I am suspecting that `pyls` expects to be in the same virtualenv as the project. 

Is that correct? And if so, is there a way around it?

**Comment by goanpeca** [comment]
Is the jedi environment setting activated correctly? This is needed for Jedi to know where to look.

See: https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L43

**Comment by halloleo** [comment]
Thanks @goanpeca! So do I have to have Jedi installed separately? And into which virtualenv? pyls's virtualenv? The source code project's virtualenv? Or into its own virtualenv?

**Comment by goanpeca** [comment]
No need. But that configuration option needs to be there so jedi can look in that environment.

**Comment by halloleo** [comment]
Indeed that was the issue. 

In Emacs' `lsp-mode` it is the configuration variable `lsp-pyls-plugins-jedi-environment` which you have to set to the path of the project's virtual environment.

Thanks again for your help.

**Comment by goanpeca** [comment]
No prob @halloleo, glad you solved the issue!
