### ISSUE TITLE
Adapt to ujson > 2.0

### ISSUE THREAD

**Issue by PureTryOut** [palantir/python-language-server#802]
ujson 2.0 has been released, but this package requires <= 1.35 currently. Please update to the latest version.

**Comment by goanpeca** [comment]
Hello. Once the windows and mac wheels are mived from test pypi to real pypi we will make the move.

There are only linux wheels available at the moment.

**Comment by e-kwsm** [comment]
[ujson 3.0.0 was released.](https://github.com/ultrajson/ultrajson/releases/tag/3.0.0)

**Comment by PureTryOut** [comment]
I wanted to update to 0.34.1 but my system having a new ujson is still a problem.
