### ISSUE TITLE
The returned VersionedTextDocumentIdentifiers from textDocument/rename have a too high document version

### ISSUE THREAD

**Issue by rwols** [palantir/python-language-server#816]
When doing a textDocument/rename, pyls will nicely suggest to open non-tracked files to open and apply the changes to.

However, the `"version"` of the files to-be-opened have their version number too high.

Here's a part of the response payload:
```js
        {
            "textDocument": {
                "uri": "file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/references.py",
                "version": 9
            },
            "edits": [
                {
                    "range": {
                        "start": {
                            "line": 0,
                            "character": 0
                        },
                        "end": {
                            "line": 182,
                            "character": 0
                        }
                    },
                    "newText": "<snip>"
                }
            ]
        },
```

The file references.py was not yet open in the editor.
In case the document is not yet tracked via a textDocument/didOpen, I suggest to put `"version": null` here as that's allowed per spec.

Right now, the `"version": 9` came from the file that ran the textDocument/rename request. It had a version number of 9 and somehow that number was used for all the files that weren't yet tracked with textDocument/didOpen.

For a newly-opened file, our internal version counter starts at `0`. If the version of the edit doesn't match we don't apply the edit, as can be seen from the console:

```
LSP: ignoring edit due to non-matching document version
```

python-language-server version: 0.33.0

**Comment by ccordoba12** [comment]
Please submit a pull request for this.
