### ISSUE TITLE
Error while Installing Pygame - "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by gtiwari912** [palantir/python-language-server#828]
![Capture](https://user-images.githubusercontent.com/67228014/86033554-bc759e00-ba56-11ea-8952-60c036abc4c9.PNG)

i m getting an error something like (below Line)
"python setup.py egg_info" failed with error code 1 in C:\Users\hp\AppData\Local\Temp\pip-install-gget9s3m\pygame\

i have also uploaded the screenshot of error hav a look

can somebody please help me out

**Comment by ccordoba12** [comment]
Your problem is completely unrelated to this package.
