### ISSUE TITLE
Error when installing STAMP

### ISSUE THREAD

**Issue by emankhalaf** [palantir/python-language-server#832]
Hello,
I am following the installation guidelines for STAMP as follows:
sudo apt-get install libblas-dev liblapack-dev gfortran
sudo apt-get install freetype* python-pip python-dev python-numpy python-scipy python-matplotlib
sudo pip install STAMP

Then I got this error:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Z5H6y6/biom-format/

I tried this:
pip install --upgrade setuptools --user python

and got this error
Requirement already up-to-date: setuptools in ./miniconda3/lib/python3.7/site-packages (49.1.0)
ERROR: Could not find a version that satisfies the requirement python (from versions: none)
ERROR: No matching distribution found for python

Need the your recommendations, please.
Eman

**Comment by ccordoba12** [comment]
Your error has nothing to do with this package, sorry. I don't understand how you arrived here to report it.

**Comment by emankhalaf** [comment]
Excuse me, do you mean it is the wrong forum to report?

**Comment by ccordoba12** [comment]
Yes, it is.
