### ISSUE TITLE
Support multiple formatters

### ISSUE THREAD

**Issue by jzelinskie** [palantir/python-language-server#847]
My end goal is to have `isort` and `black` both executing when "format document" is called.
I think the best way to accomplish this is to specify an ordered list of formatters.
If I was to implement this like a regular formatting plugin, would I have any issues?
I assume there'd be a problem because `@hookimpl` would be executed when you import an existing formatter into the meta-formatter.

**Comment by theHamsta** [comment]
There's a a extension for isort. See 3rd party plugins in README.

**Comment by jzelinskie** [comment]
I could be mistaken, but it appears that either the isort plugin does not work (I've tried a branch both the pypi version and the git rev PRed for adding isort 5+ compatibility). If it did work, would pyls format with both? How would it know which to execute first?

**Comment by theHamsta** [comment]
Hi. I just tried it out. The extension seems to work only with isort==4.0.X. Nothing happens with isort==5.0.9. Then, it uses both formatters.

EDIT: latest working I found was 4.3.21

**Comment by jzelinskie** [comment]
pyls-isort appears to be updated and working. My bad for the confusion.
