### ISSUE TITLE
Install Error!!!

### ISSUE THREAD

**Issue by TheSpyderBlip** [palantir/python-language-server#877]
I followed the instructions to installing ide-python as on the website: https://github.com/palantir/python-language-server/

I first ran a command on cmd to install the python language server: `python -m pip install python-language-server[all]`
Here is what went on next :

`Collecting python-language-server[all]
Using cached python_language_server-0.35.1-py2.py3-none-any.whl (50 kB)
Collecting python-jsonrpc-server>=0.4.0
Using cached python_jsonrpc_server-0.4.0-py3-none-any.whl (8.9 kB)
Collecting jedi<0.18.0,>=0.17.0
Using cached jedi-0.17.2-py2.py3-none-any.whl (1.4 MB)
Collecting pluggy
Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting ujson>=3.0.0; python_version > "3"
Using cached ujson-4.0.1.tar.gz (7.1 MB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing wheel metadata ... done
Collecting pydocstyle>=2.0.0; extra == "all"
Using cached pydocstyle-5.1.1-py3-none-any.whl (35 kB)
Requirement already satisfied: flake8>=3.8.0; extra == "all" in c:\users\shivani\appdata\local\programs\python\python39-32\lib\site-packages (from python-language-server[all]) (3.8.4)
Collecting yapf; extra == "all"
Using cached yapf-0.30.0-py2.py3-none-any.whl (190 kB)
Collecting rope>=0.10.5; extra == "all"
Using cached rope-0.18.0.tar.gz (249 kB)
Requirement already satisfied: autopep8; extra == "all" in c:\users\shivani\appdata\local\programs\python\python39-32\lib\site-packages (from python-language-server[all]) (1.5.4)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0; extra == "all" in c:\users\shivani\appdata\local\programs\python\python39-32\lib\site-packages (from python-language-server[all]) (2.2.0)
Requirement already satisfied: pycodestyle<2.7.0,>=2.6.0; extra == "all" in c:\users\shivani\appdata\local\programs\python\python39-32\lib\site-packages (from python-language-server[all]) (2.6.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0; extra == "all" in c:\users\shivani\appdata\local\programs\python\python39-32\lib\site-packages (from python-language-server[all]) (0.6.1)
Collecting pylint>=2.5.0; extra == "all"
Using cached pylint-2.6.0-py3-none-any.whl (325 kB)
Collecting parso<0.8.0,>=0.7.0
Using cached parso-0.7.1-py2.py3-none-any.whl (109 kB)
Collecting snowballstemmer
Using cached snowballstemmer-2.0.0-py2.py3-none-any.whl (97 kB)
Requirement already satisfied: toml in c:\users\shivani\appdata\local\programs\python\python39-32\lib\site-packages (from autopep8; extra == "all"->python-language-server[all]) (0.10.1)
Collecting astroid<=2.5,>=2.4.0
Using cached astroid-2.4.2-py3-none-any.whl (213 kB)
Collecting colorama; sys_platform == "win32"
Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting isort<6,>=4.2.5
Using cached isort-5.6.4-py3-none-any.whl (98 kB)
Collecting six~=1.12
Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Processing c:\users\shivani\appdata\local\pip\cache\wheels\41\20\07\2a3e02cdfc8b442404202f6ef99ff1b1c16b73910968a46f2f\lazy_object_proxy-1.4.3-cp39-cp39-win32.whl
Collecting wrapt~=1.11
Using cached wrapt-1.12.1.tar.gz (27 kB)
Using legacy 'setup.py install' for rope, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
Building wheels for collected packages: ujson
Building wheel for ujson (PEP 517) ... error
_ERROR: Command errored out with exit status 1:
command: 'C:\Users\SHIVANI\AppData\Local\Programs\Python\Python39-32\python.exe' 'C:\Users\SHIVANI\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip_vendor\pep517_in_process.py' build_wheel 'C:\Users\Public\Documents\Wondershare\CreatorTemp\tmp2nex_ym6'
cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-m1nz75zj\ujson
Complete output (5 lines):
running bdist_wheel
running build
running build_ext
building 'ujson' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
ERROR: Failed building wheel for ujson
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly_`

Can anyone explain this to me.

Thank You In Advance!!
![pide](https://user-images.githubusercontent.com/73152282/96676975-3fb35a80-138c-11eb-8187-b1442fd89e51.png)
![Screenshot_1](https://user-images.githubusercontent.com/73152282/96676979-40e48780-138c-11eb-91b1-6e19534762a3.png)

**Comment by ccordoba12** [comment]
> 'C:\Users\SHIVANI\AppData\Local\Programs\Python\Python39-32

You're using a 32 bit build of Python, which is not supported by one of our dependencies (ujson). Please install a 64 bit build, which won't show this problem.

If that's not possible for you, I'm afraid there's nothing we can do about it, sorry. Most computers these days are 64 bit, so most projects don't support 32 bit architectures anymore.

**Comment by TheSpyderBlip** [comment]
And what about the 

> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by ccordoba12** [comment]
Ujson is a compiled library. Since pip can't find a binary wheel for your Python version, it's trying to compile it using Visual Studio 14 and it's reporting it as not present in your computer.
