### ISSUE TITLE
How to start python server?

### ISSUE THREAD

**Issue by madatbay** [palantir/python-language-server#923]
Hi, I'm working on a some how browser based code editor project. To enable autocomplete for python in `monaco editor` I need use language server and connect via websocket from client side. For this I'm trying to use `jsonrpc-ws-proxy` as a language server proxy and proxy need to start python language server to use it. How to start python language server? 
I have already installed it to venv:
`pip install python-language-server`

**Comment by pipiliang** [comment]
[pyls -v](https://github.com/pipiliang/code.py/blob/main/codepy-server/src/main.py)
