### ISSUE TITLE
Line length configuration

### ISSUE THREAD

**Issue by voider1** [palantir/python-language-server#93]
How can I configure it to not complain about 79 limit? I've already tried ~/.config/pycodestyle, but that didn't work.

**Comment by gatesn** [comment]
We look for `['tox.ini', 'pep8.cfg', 'setup.cfg', 'pycodestyle.cfg']` within the repository. Happy to create an issue to read config from root as well?

**Comment by voider1** [comment]
@gatesn I've installed the extension through pip, how can I alter the config? Where should I put the file?

**Comment by gatesn** [comment]
The workspace you're opening in your client should configure its own settings.

**Comment by voider1** [comment]
@gatesn I'm using Neovim, how would I do that? In the init.vim?

**Comment by gatesn** [comment]
There is currently no way to configure settings on a language-server wide basis. Instead, it will use the workspace root given to it by neovim and look in there for config files. I'm not sure how neovim discovers the workspace root.

**Comment by voider1** [comment]
@gatesn So I should put a config in the place where Neovim gets it init.vim?

**Comment by gatesn** [comment]
Closing for #57
