### ISSUE TITLE
feature request: semantic highlighting (textDocument_semanticTokens)

### ISSUE THREAD

**Issue by smemsh** [palantir/python-language-server#933]
Feature request to support textDocument_semanticTokens, now part of official LSP standard:

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens

Personally I would use this with [vim-lsp](https://github.com/prabirshrestha/vim-lsp) which has [implemented support for it](https://github.com/prabirshrestha/vim-lsp/pull/464).

**Comment by andfoy** [comment]
Hi @smemsh, since Palantir stopped the maintenance of this repository, all active development has moved to https://github.com/python-lsp-server, could you please open an issue about this feature there?

**Comment by Alexey-T** [comment]
https://github.com/python-lsp-server - wrong URL.

**Comment by andfoy** [comment]
Sorry, https://github.com/python-lsp/python-lsp-server

**Comment by smemsh** [comment]
python-lsp/python-lsp-server#33
