### ISSUE TITLE
Missing support for flake8 --extend-ignore

### ISSUE THREAD

**Issue by cippaciong** [palantir/python-language-server#941]
Hello, I'm using `pyls` on `neovim` with the [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) plugin.
I'm formatting my code using `black` and have the following settings configured in `setup.cfg`, as suggested by the [Black documentation](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length):
```ini
[flake8]
max-line-length = 88
select = C,E,F,W,B,B950
extend-ignore = E203, E501, W503
```
My problem is that the `extend-ignore` line is ignored by `pyls` and I have warnings in my editor that I shouldn't have. 

Looking at [flake8_lint.py#L25](https://github.com/palantir/python-language-server/blob/a91a257d2c8687a7931721d387b2ffeb6aa71fc2/pyls/plugins/flake8_lint.py#L25) and [flake8_conf.py#L26](https://github.com/palantir/python-language-server/blob/a91a257d2c8687a7931721d387b2ffeb6aa71fc2/pyls/config/flake8_conf.py#L26) I think that the problem might be that `pyls` is looking only for the `ingore` option.

**Comment by ccordoba12** [comment]
Hey @cippaciong, thanks for reporting. You're welcome to submit a pull request to fix this.

**Comment by cippaciong** [comment]
Hi @ccordoba12, I gave it a try (I moved from python-language-server to python-lsp-server in the meantime) but I'm stuck with an error that I'm having a hard time to understand.

You can see my changes here: https://github.com/cippaciong/python-lsp-server/commit/e4f84e515cd1bbd92bf8a02dd54628a0c038b42d

From the logs it looks like `flake8` is invoked correctly:
```
2021-09-01 00:39:39,717 CEST - DEBUG - pylsp.plugins.flake8_lint - Got flake8 settings: {'select': ['C', 'E', 'F', 'W', 'B', 'B950'], 'enabled': True, 'extendIgnore': ['E203', 'E501', 'W503'], 'maxLineLength': 88}
2021-09-01 00:39:39,717 CEST - DEBUG - pylsp.plugins.flake8_lint - Calling flake8 with args: '['-', '--extend-ignore=E203,E501,W503', '--max-line-length=88', '--select=C,E,F,W,B,B950']'
```
But than I have this weird log line where it mixes a proper warning for `E303` with a `flake8` error `unrecognized arguments: --extendIgnore=E203,E501,W503\n`
```
2021-09-01 00:39:39,897 CEST - DEBUG - pylsp.config.config -   finish pylsp_lint --> [[{'source': 'flake8', 'range': {'start': {'line': 0, 'character': 0}, 'end': {'line': 0, 'character': 1}}, 'code': 'ERR', 'message': 'usage: flake8 [optio
ns] file file ...\nflake8: error: unrecognized arguments: --extendIgnore=E203,E501,W503\n', 'severity': 1}], [{'source': 'flake8', 'code': 'E303', 'range': {'start': {'line': 34, 'character': 4}, 'end': {'line': 34, 'character': 40}}, 'mess
age': 'E303 too many blank lines (2)', 'severity': 2}]] [hook]
```

Do you have any idea of what's happening here?

P.S. Let me know if you want me to move the discussion to the `python-lsp-server` repo

**Comment by ccordoba12** [comment]
Yes, please open an issue in `python-lsp-server` because this project is abandoned.

**Comment by cippaciong** [comment]
Moved to https://github.com/python-lsp/python-lsp-server/issues/76
