### ISSUE TITLE
Frequently hanging on Windows

### ISSUE THREAD

**Issue by deathaxe** [palantir/python-language-server#96]
After fixing crashes (#95) caused by invalid path translations, Sublime Text still freezes frequently, while editing. In such situations python.exe which runs the pyls seems to run in an endless loop consuming 100% CPU. Killing the process causes ST to work normally again.

Something seems to cause a deadlock which blocks the whole stdin/stdout communication.

The logfile does not contain any errors/warnings.

### Setup
- Windows 10 1703 x64
- Sublime Text 3 4142 with LSP package
- python-language-server 0.4.1
- both connected via stdin/stdout interface
- python 3.6.2 x64

**Comment by gatesn** [comment]
My suspicion would be that on Windows, this isn't the correct base case to break out of the loop: https://github.com/palantir/python-language-server/blob/develop/pyls/config.py#L79

**Comment by deathaxe** [comment]
Seems to be the point. Investigating ...
